PaddlePaddle/PaddleScience

- docs/source/conf.py
> Enable EditOnGithub in `conf.py`

- docs/source/index.rst
> fix word typo in doc

- README.md
- docs/source/getting_started/installation.rst
This PR updates readme and doc completing hardware requirements.
> complete hardware requirements in doc and readme

- README.md
- docs/source/getting_started/installation.rst
- docs/source/index.rst
- examples/darcy2d/README.md
- examples/laplace2d/README.md
- examples/ldc2d/README.md
This PR modify absolute link to relative link.
> relative link of images

- README.md
- docs/source/index.rst
This PR removes "pre-release" in readme and doc.
> remove pre-release in doc

- paddlescience/solver/solver.py
> [Fix Bug]fix the checkpoint bug

- tests/test_api/backward.py
modify the compare accuracy with numerical gradient and auto differentiation
> modify test accuracy settings

- tests/test_examples/run.sh
skip test_ldc2d_t case for fix ldc2d_t example
> skip test_ldc2d_t case

- examples/ldc2d_t/ldc2d_t.py
- paddlescience/geometry/rectangular.py
- paddlescience/loss/loss_L2.py
> modify the related ic_value

- tests/test_examples/run.sh
- tests/test_examples/test_ldc2d_t.py
> modify the ldc2d_t case

- paddlescience/visu/__init__.py
- paddlescience/visu/visu_vtk.py
- requirements.txt
This PR enhance vtk visualizaition with pointwise output.
> add vtk points

- paddlescience/visu/visu_vtk.py
This PR enhances vtk visualisation with multiple data on one geometry.
> enhance vtk visu multiple data

- tests/run.sh
- tests/test_api/run.sh
- tests/test_models/run.sh
> skip distributed cases

- tests/run.sh
> modify exec file

- examples/cylinder/2d_unsteady_continuous/README.md
- examples/fsi/README.md
> Fix README.md format.

- tests/test_models/test_ldc2d_unsteady_t.py
fix ldc2d_unsteady test case
distributed test
> fix ldc2d_unsteady test case

- tests/test_models/run.sh
add 3d_unsteady_base distributed test case
> add 3d_unsteady_base distributed case

- examples/laplace/README.md
- paddlescience/pde/pde_poisson.py
This PR includes two updates:
- fix warnings on dcu platform
- update readme using 0,1 devices
> fix warings in dcu platform

- examples/cylinder/3d_unsteady_discrete/optimize/cylinder3d_unsteady_optimize.py
modify the .vtu path of optimize version
> modify the .vtu path of optimize version

- examples/cylinder/3d_unsteady_discrete/optimize/utils.py
修改数据切分， 适配  3D 圆柱扰流 10 loss 版本
> Adapt data partition for Cylinder with 10 losses version

- Dockerfile.rocm
This PR adds dockerfile for DCU platform
> dockerfile for dcu platform

- paddlescience/solver/solver.py
move new executor to psci 
功能描述：
将新执行器放入到套件中，在静态图中默认开启以达到更高的性能表现。
> move new executor

- paddlescience/solver/solver.py
Reverts PaddlePaddle/PaddleScience#84
> Revert "move new executor"

- tests/test_models/run_framework.sh
> ci_framework1

- paddlescience/solver/solver.py
- requirements.txt
add visualDL for psci
功能描述：
在套件中增加visualDL 可视化的功能。目前单机中的动态图和静态图都已经加上，效果如下：
需要注意的是，目前分布式尚不支持，这是因为分布式训练使用时，采用了fit()接口，在该接口中进行多轮迭代。每一步的loss信息打印也在框架接口中实现。接口外，即套件中拿不到相关信息。
> add visualDL for psci

- .github/PULL_REQUEST_TEMPLATE.md
> pr template, test=document

- paddlescience/algorithm/algorithm_pinns.py
- paddlescience/geometry/__init__.py
- paddlescience/loss/loss_L2.py
- paddlescience/pde/pde_base.py
Bug fixes
Functionalities
This PR improves support of discrete geometry fixing some bugs.
> improve support of disc geometry

- examples/cylinder/3d_unsteady_discrete/optimize/cylinder3d_unsteady_optimize.py
- paddlescience/__init__.py
- paddlescience/config.py
New features
Others
add warpper in psci config
功能描述：
将paddle特有的开关项，例如enable_static()、enable_prim()等封装在套件中。
> add warpper in psci config

- examples/cylinder/2d_unsteady_continuous/loading_cfd_data.py
Bug fixes
Others
This PR fix data reader mismatch issue.
> bug fix in data reader

- paddlescience/algorithm/algorithm_pinns.py
- paddlescience/labels/labels.py
- paddlescience/solver/solver.py
New features
Others
Get the shape when use new-ad
> Get the shape when use new-ad

- paddlescience/solver/solver.py
Bug fixes
Others
Fix data shape bug in laplace example.
> Fix data shape bug in laplace example.

- paddlescience/loss/loss_base.py
Others 
Others
Delete batch_jacobian and batch_hessian.
> Delete batch_jacobian and batch_hessian.

- tests/test_models/run.sh
> set new dynamic graph

- paddlescience/config.py
- paddlescience/loss/loss_L2.py
- paddlescience/solver/solver.py
New features 
Others
This PR adapts new ad usage: norm 1 and prim2org.
> adapt new ad

- paddlescience/loss/loss_base.py
- paddlescience/pde/pde_base.py
- paddlescience/pde/pde_laplace.py
- paddlescience/pde/pde_navier_stokes.py
- paddlescience/pde/pde_poisson.py
APIs
This PR updates PDE definition.
> update equation definition

- paddlescience/network/network_fc.py
- paddlescience/solver/solver.py
- tests/test_api/test_FCNet.py
New features 
APIs
This PR add initialize function in network, which support detail initialization of network.
> net init in detail

- paddlescience/loss/loss_base.py
Bug fixes
Others
This PR fix numpy import error.
> fix numpy import error

- examples/laplace/laplace2d.py
- paddlescience/config.py
- paddlescience/solver/solver.py
- paddlescience/solver/utils.py
New features
Others
As title. 为`psci.solver.Solver`接口添加CINN支持，这样无论是运行laplace2d模型还是baseline版本的3D圆柱绕流模型都不需要在模型代码中添加过多代码。只需添加
```
psci.config.cinn_enabled()
```
即可
> `psci.solver` support CINN

- paddlescience/solver/solver.py
Bug fixes
APIs
This PR fix api usage in creating input and label.
> fix issue in solver create label

- paddlescience/algorithm/algorithm_pinns.py
- paddlescience/optimizer/optimizer.py
- paddlescience/solver/solver.py
- paddlescience/visu/visu_vtk.py
Others
Docs 
Update the doc for algo, opt, solver and visu.
功能描述：
更新算法、优化器、求解器以及可视化的文档。
效果如下：
> Update the doc for algo, opt, solver and visu.

- paddlescience/algorithm/algorithm_pinns.py
- paddlescience/inputs/inputs.py
- paddlescience/labels/labels.py
- paddlescience/loss/loss_formula.py
- paddlescience/network/network_fc.py
New features
APIs
This PR fix weight/rhs issue in individual loss definition.
> individual loss definition fix

- paddlescience/algorithm/algorithm_pinns.py
- paddlescience/loss/__init__.py
- paddlescience/network/network_fc.py
- paddlescience/solver/solver.py
OPs
This PR adds switcher to create labels and inputs (from pde or from individual loss).
> swtich pde/loss input creation

- paddlescience/algorithm/algorithm_pinns.py
Others
Others
This PR removes print in code.
> remove print

- examples/cylinder/3d_unsteady_discrete/optimize/cylinder3d_unsteady_optimize.py
- paddlescience/algorithm/algorithm_pinns.py
Bug fixes
API
This PR fix issue in 3d cylinder optimize version, due to some internal api modification.
> fix 3d cylinder optimize bug

- examples/cylinder/2d_unsteady_continuous/cylinder2d_unsteady_train_newapi.py
- examples/cylinder/2d_unsteady_continuous/loading_cfd_data.py
- paddlescience/visu/visu_vtk.py
New features
Others
This PR writes 2d cylinder case with new api.
> 2d unsteady continus with new api

- paddlescience/loss/loss_L2.py
New features
APIs
This PR adds l2 loss definition in L2.
> add weight config in l2 loss definition

- paddlescience/algorithm/algorithm_pinns.py
Bug fixes
Others
For dist case with user inputs, this PR fix padding issue.
> Padding in creation inputs from loss

- paddlescience/__init__.py
- paddlescience/config.py
Bug fixes
Others
Only use the env flag `FLAGS_use_cinn` to control CINN.
> Only use the env flag to control CINN.

- paddlescience/algorithm/algorithm_pinns.py
- paddlescience/loss/loss_L2.py
- paddlescience/loss/loss_base.py
- paddlescience/loss/loss_formula.py
- paddlescience/network/network_fc.py
New features
Others
This PR adds parameter "params" in internal functions, which can be used for specific net's weight.
> add params in loss computing

- paddlescience/network/network_fc.py
Bug fixes
Others
This PR fix initializer issue. It was not created in initializer.
> add param in initialize

- paddlescience/network/network_fc.py
Others
Docs
This PR updates documentation of activation input in network.
> update doc for activation input

- examples/cylinder/3d_steady/cylinder3d_steady.py
- examples/cylinder/3d_unsteady_discrete/baseline/cylinder3d_unsteady.py
- examples/cylinder/3d_unsteady_discrete/optimize/cylinder3d_unsteady_optimize.py
- examples/darcy/darcy2d.py
- examples/kovasznay/kovasznay.py
- examples/laplace/laplace2d.py
- examples/ldc/ldc2d_steady_train.py
- examples/ldc/ldc2d_unsteady_t.py
- tests/config/cylinder3d_steady.yaml
- tests/config/cylinder3d_unsteady.yaml
- tests/config/cylinder3d_unsteady_optimize.yaml
- tests/config/darcy2d.yaml
- tests/config/kovasznay.yaml
- tests/config/ldc2d_steady_train.yaml
- tests/config/ldc2d_unsteady_t.yaml
Others
Others
Add config in 7 models.
> Add config in 7 models.

- tests/config/CI/laplace2d.yaml
- tests/models/configtrans.py
- tests/models/generate.py
- tests/models/runcase.py
> config test framwork

- tests/models/generate.py
Others
Others
fix case generate file
> fix case generate

- examples/cylinder/3d_steady/cylinder3d_steady.py
- examples/cylinder/3d_unsteady_discrete/baseline/cylinder3d_unsteady.py
- examples/cylinder/3d_unsteady_discrete/optimize/cylinder3d_unsteady_optimize.py
- examples/darcy/darcy2d.py
- examples/kovasznay/kovasznay.py
- examples/ldc/ldc2d_steady_train.py
- examples/ldc/ldc2d_unsteady_t.py
Others
Others
Add save_npy func in 7 models.
> Add save_npy func in 7 models.

- paddlescience/loss/loss_base.py
OPs 
This PR updates index computation for order 2, uniforming u_xx and u_x_y.
> update index computation for order 2

- paddlescience/solver/solver.py
- paddlescience/solver/utils.py
OPs
This PR adds timer in solver, which can record time.
> add timer in solver

- tests/config/CI/darcy.yaml
- tests/config/CI/kovasznay.yaml
- tests/config/CI/ldc2d_steady.yaml
- tests/models/run.sh
Others
Others
add config cases
> add config cases

- paddlescience/loss/loss_base.py
- paddlescience/pde/__init__.py
- paddlescience/pde/pde_plate_equilibrium.py
New features
APIs
This PR adds 4-order derivative computation and 4-order equibrium equation.
> four order grad and plat equ equation

- paddlescience/solver/solver.py
Bug fixes
Others
Fix bug of loading model in train.
> Fix bug of loading model in train.

- examples/cylinder/3d_steady/cylinder3d_steady.py
- examples/ldc/ldc2d_unsteady_t.py
- paddlescience/visu/visu_vtk.py
- tests/config/ldc2d_unsteady_t.yaml
Bug fixes
Others 
Fix save_npy bug and add time config.
功能描述：
1. 解决了save_npy的bug，bug是因为几何坐标和物理信息长度不一样导致
2. 在配置参数中增加了时间项
> Fix cylinder3d steady bug

- paddlescience/network/network_fc.py
New features
APIs
This PR adds more act function in string format.
> more act functions in string format

- paddlescience/loss/loss_L2.py
- paddlescience/loss/loss_base.py
OPs
This PR adds parameter "params" in derivative function call, which is potentially used.
> add params in functions der

- examples/cylinder/3d_unsteady_discrete/README.md
- examples/cylinder/3d_unsteady_discrete/optimize/cylinder3d_unsteady_optimize.py
Others
Others
This PR enable cinn pass for cylinder example to run with prim op.
The functionality depends on the improvement of Paddle https://github.com/PaddlePaddle/Paddle/pull/45531/.
> [CINN] add cinn pass for cylinder example with prim op

- paddlescience/pde/pde_poisson.py
Bug fixes
APIs
This PR fix 1d poisson error, which was not defined.
> fix poission 1d 1 dim error

- paddlescience/solver/solver.py
Others
- improve autoparallel engine api
> [AutoParallel] improve api

- paddlescience/loss/loss_base.py
Others
Others
This pr fix p_norm in new ad with porder=1
修复后的p=1
之前workround：
> Fix p norm

- paddlescience/algorithm/algorithm_pinns.py
- paddlescience/bc/bc.py
- paddlescience/geometry/geometry.py
- paddlescience/loss/loss_L2.py
- paddlescience/loss/loss_base.py
- paddlescience/pde/pde_base.py
- tests/test_api/test_Neumann.py
- tests/test_api/test_Robin.py
Bug fixes
APIs
This PR fix Neumann condition bug. This error regards to normal direction.
> Fix neumann boundary condition

- paddlescience/solver/solver.py
Others
Others
This PR modify loss.numpy()[0] to float(loss) to adapt 0 tensor support modification.
> tensor 0 dim modification

- paddlescience/module/cfd/pinn_solver.py
- paddlescience/module/fsi/viv_pinn_solver.py
Others
Others
This PR modify files in module directory for 0-tensor.
> 0 tensor for files in module

- paddlescience/visu/visu_vtk.py
Bug fixes
APIs
修复了静态图数据并行时，`save_npy`未对`data`做数据切分导致保存报错的问题
> fix(save_npy): fix save_npy in auto_dist mode

- paddlescience/neo_geometry/inflation.py
- paddlescience/neo_geometry/mesh.py
- requirements.txt
Bug fixes
Requirements
由于安装速度问题，暂时移除requirement中open3d和pymesh的依赖，改为warning提醒
> remove open3d and pymesh from requirements

- examples/cylinder/2d_steady/train_enn.py
- examples/cylinder/2d_steady/train_transformer.py
- examples/lorenz/train_enn.py
- examples/lorenz/train_transformer.py
- examples/rossler/train_enn.py
- examples/rossler/train_transformer.py
Bug fixes
Others
修复调用build_dataloader错误
> fix bulid dataloader

- ppsci/constraint/__init__.py
- ppsci/constraint/boundary_constraint.py
- ppsci/constraint/initial_constraint.py
- ppsci/constraint/integral_constraint.py
- ppsci/constraint/interior_constraint.py
- ppsci/constraint/periodic_constraint.py
- ppsci/constraint/supervised_constraint.py
- ppsci/equation/pde/navier_stokes.py
- ppsci/geometry/geometry.py
- ppsci/geometry/geometry_1d.py
- ppsci/geometry/geometry_nd.py
- ppsci/geometry/mesh.py
- ppsci/geometry/pointcloud.py
- ppsci/geometry/timedomain.py
- ppsci/loss/__init__.py
- ppsci/loss/l1.py
- ppsci/loss/l2.py
- ppsci/loss/mse.py
- ppsci/solver/printer.py
- ppsci/solver/solver.py
- ppsci/solver/train.py
- ppsci/utils/config.py
- ppsci/validate/geo_validator.py
New features
APIs
1. 完善`geometry`模块的周期数据点生成函数`periodic_point`
2. 添加周期边界条件 `PeriodicConstraint`
3. 添加3个周期边界条件专用损失函数 `PeriodicL1Loss`，`PeriodicL2Loss`，`PeriodicMSELoss`
4. 支持学习率为普通浮点数的情况，此时lr_scheduler为None，因此所有涉及获取学习率的代码改为`optimizer.get_lr`而不是`lr_scheduler.get_lr`，同时在调节学习率时增加了对lr_scheduler为None的判断
5. 更改所有Constraint中，for循环中使用的变量名`label_expr`为`expr`，防止与入参`label_expr`同名而引起潜在的问题
6. 添加config.py文件，避免在solver.py中import报错
周期边界约束数据构造和损失计算逻辑：
指定batchsize=N（必须是正偶数）时，以一个batch数据为例，会生成N/2个原始点，根据原始点生成N/2个周期点，将原始点和周期点在axis=0上叠加作为真正的输入数据；同理在Loss计算时，使用输出的前半部分（N/2个原始点的对应输出）和后半部分（N/2个周期点的对应输出）计算损失值。由于数据构造要求原始点、周期点严格相间排列，因此需要固定shuffle=False且N为正偶数，避免dataloader根据随机index加载数据而引起错误的周期约束
> Add periodic constraint

- paddlescience/solver/utils.py
Bug fixes
APIs
主要修改点：
1. 根据 PaddlePaddle/Paddle/pull/50425 的修改，删除 `utils.py` 中的对于 `with_data_parallel`的调用，关键修改处在![image](https://user-images.githubusercontent.com/23737287/228542713-e03298f8-0cac-47fa-a2df-a52bccb17ca6.png)
其他：
1. 按最新pre-commit插件，用isort+black格式化了 `utils.py`，并调整了部分import的写法
> remove with_data_parallel in utils.py

- examples/cylinder/2d_unsteady/transformer_physx/train_enn_v2.py
- examples/cylinder/2d_unsteady/transformer_physx/train_transformer_v2.py
- examples/lorenz/train_enn_v2.py
- examples/lorenz/train_transformer_v2.py
- examples/rossler/train_enn_v2.py
- examples/rossler/train_transformer_v2.py
- ppsci/arch/embedding_koopman.py
- ppsci/arch/physx_transformer.py
Bug fixes 
Others
1.  修改数据集配置变量名称“train_dataloader" -> "train_dataloader_cfg"；
2. 修改拼写错误；
3. 修改了不合适的数据集配置；
> fix bugs in transformer-physx

- docs/zh/examples/cylinder2d_unsteady_transformer_physx.md
- docs/zh/examples/lorenz.md
- docs/zh/examples/rossler.md
- examples/cylinder/2d_unsteady/transformer_physx/train_enn_v2.py
- examples/cylinder/2d_unsteady/transformer_physx/train_transformer_v2.py
- examples/fsi/viv.py
- examples/lorenz/train_enn_v2.py
- examples/lorenz/train_transformer_v2.py
- examples/rossler/train_enn_v2.py
- examples/rossler/train_transformer_v2.py
- ppsci/data/dataset/mat_dataset.py
- ppsci/data/dataset/trphysx_dataset.py
Others
Docs
1. 更新 transformer-physx 案例及文档；
2. 修复trphysx_dataset.py中数据集参数weight_dict为None时的错误问题；
3. 修复MatDataset的type hint;
> update transformer-physx docs

- ppsci/arch/embedding_koopman.py
- ppsci/autodiff/ad.py
- ppsci/constraint/base.py
- ppsci/constraint/boundary_constraint.py
- ppsci/constraint/initial_constraint.py
- ppsci/constraint/integral_constraint.py
- ppsci/constraint/periodic_constraint.py
- ppsci/data/dataloader.py
- ppsci/data/dataset/array_dataset.py
- ppsci/data/dataset/csv_dataset.py
- ppsci/data/dataset/mat_dataset.py
- ppsci/data/process/transform/preprocess.py
- ppsci/equation/pde/base.py
- ppsci/geometry/geometry.py
- ppsci/optimizer/lr_scheduler.py
- ppsci/optimizer/optimizer.py
- ppsci/solver/solver.py
- ppsci/utils/misc.py
- ppsci/utils/profiler.py
- ppsci/utils/save_load.py
- ppsci/validate/base.py
- ppsci/validate/geo_validator.py
- ppsci/visualize/base.py
Others 
Docs
主要修改点：
完善 type hint
> Refine type hint

- docs/zh/examples/cylinder2d_unsteady.md
- ppsci/arch/model_list.py
- ppsci/solver/solver.py
APIs
主要修改点：
1. 完善 `Solver.predict` 方法，支持按 batch size 进行预测
其他：
1. 修复 `ModelList.forward` 多次调用 transform的问题，改为直接调用 `submodel.forward`
2. 修复cylinder2d_Re100文档中的一处代码引用错误
> support batch-size prediction

- paddlescience/network/grad_norm.py
- requirements.txt
- tests/test_api/test_GradNorm.py
Bug fixes
APIs
主要修改点：
1. 给 `cal_gradnorm` 计算的每一项 loss 手动shape成 0-D tensor
2. `requirements.txt` 添加 `tqdm` 库
> unify loss item to 0-D tensor in cal_gradnorm

- docs/zh/contribute.md
- mkdocs.yml
Others
Docs
主要修改点：
1. 完善贡献指南文档，更正错误的标题编号，并在末尾添加 代码风格规范 说明
其他：
1. 根据 squidfunk/mkdocs-material#5160 修复公告，重新添加回 `search.highlight` 和 `navigation.instant` 两个配置
> Refine contribute doc

- docs/index.md
- docs/zh/api/utils.md
- mkdocs.yml
- ppsci/data/__init__.py
- ppsci/data/dataset/csv_dataset.py
- ppsci/utils/__init__.py
- ppsci/utils/checker.py
- ppsci/utils/misc.py
- pyproject.toml
Others
Docs
主要修改点：
1. 完善首页的安装步骤
2. 添加基础 PaddleScience 功能运行检查函数
其他修改点：
1. 取消 set_random_seed 中 rank 的参与，使得实际种子完全由参数 seed 控制
> refine setup doc and add simple running checker

- examples/euler_beam/euler_beam.py
Bug fixes
Others
修复euler_beam中visualizer未添加关键字参数引发的错误
> fix visualizer in euler beam

- docs/zh/examples/cylinder2d_unsteady.md
- docs/zh/examples/ldc2d_unsteady.md
- docs/zh/examples/viv.md
Others 
Docs 
主要修改点：
1. 添加 `cylinder2d_unsteady`, `ldc2d_unsteady`, `viv` 三个案例的 AIStudio 项目链接
> update AIStudio link button

- docs/zh/examples/cylinder2d_unsteady.md
- docs/zh/examples/ldc2d_unsteady.md
- examples/cylinder/2d_unsteady/cylinder2d_unsteady_Re100.py
- examples/ldc/ldc2d_unsteady_Re10.py
Others 
Docs 
主要修改点：
1. `cylinder2d_unsteady`、`ldc2d_unsteady` 案例中超参数变量名改为大写，同时修改了对应文档
其他：
1. 删除 `examples/ldc/ldc2d_unsteady_Re10.py` 可视化数据中单独对 boundary 的采样操作，合并至 interior 采样，同时修改对应文档
> change constant hyper parameter to uppercase

- ppsci/solver/eval.py
- ppsci/solver/solver.py
- ppsci/solver/train.py
- ppsci/solver/visu.py
Others 
APIs 
主要修改点：
1. 更新 L-BFGS 的训练代码
其他：
1. 移除 `add_LBFGS_train`、`_autocast_context_manager` 前面表示protected语义的下划线
2. 修复 `Solver.predict` 的typehint
> correct LBFGS code

- docs/zh/examples/laplace2d.md
Others
Docs
添加laplace2d AIStudio 案例链接
> add AIStudio link button of laplace2d

- examples/euler_beam/euler_beam.py
Others
Others
更新euler beam案例，将原有的一个边界条件拆分为四个边界条件
> update euler beam example

- docs/zh/examples/darcy2d.md
- ppsci/constraint/initial_constraint.py
- ppsci/data/dataset/csv_dataset.py
- ppsci/geometry/pointcloud.py
- ppsci/validate/geo_validator.py
- ppsci/visualize/visualizer.py
Others 
Docs 
主要修改点：
1. 移除几处无用 imports
2. 添加 Darcy2D 的 AIStudio 案例链接
> Add darcy2d aistudio

- docs/zh/examples/cylinder2d_unsteady.md
- examples/cylinder/2d_unsteady/cylinder2d_unsteady_Re100.py
- examples/cylinder/2d_unsteady/download_dataset.py
- examples/darcy/darcy2d.py
- examples/ldc/ldc2d_steady_Re10.py
- ppsci/constraint/boundary_constraint.py
- ppsci/constraint/initial_constraint.py
- ppsci/constraint/integral_constraint.py
- ppsci/constraint/interior_constraint.py
- ppsci/constraint/periodic_constraint.py
- ppsci/data/dataset/csv_dataset.py
- ppsci/data/dataset/mat_dataset.py
- ppsci/geometry/geometry.py
- ppsci/geometry/pointcloud.py
- ppsci/geometry/timedomain.py
- ppsci/solver/solver.py
- ppsci/solver/train.py
- ppsci/utils/download.py
- ppsci/utils/save_load.py
- ppsci/validate/geo_validator.py
- ppsci/visualize/visualizer.py
- ppsci/visualize/vtu.py
Others 
APIs
主要修改点：
1. 修复 cylinder2d_unsteady_Re100 案例中可视化数据经过了shuffle，导致可视化结果不正确的问题，并修正了文档中的一些描述问题
2. 添加 cylinder2d_unsteady_Re100 数据集的下载地址，更新对应的下载脚本
其他：
1. 统一 PointCloud 的 dim_keys 为 Tuple 类型
2. 完善个别模块的打印信息
> Fix cylinder2d and other details

- docs/zh/examples/cylinder2d_unsteady_transformer_physx.md
Others
Docs
添加 cylinder2d Transformer-physx AIStudio体验链接
> add cylinder2d(transformer-physx) aistudio

- ppsci/solver/train.py
Others
Others
update train for lbfgs
> update train for lbfgs

- docs/zh/examples/lorenz.md
Others
Docs
增加Lorenz案例的AIStudio链接
> add lorenz aistudio

- docs/zh/api/data/dataset.md
- docs/zh/api/equation.md
- docs/zh/api/geometry.md
- docs/zh/api/lr_scheduler.md
- docs/zh/api/metric.md
- docs/zh/api/utils.md
- examples/cylinder/3d_unsteady_discrete/cylinder3d_unsteady.py
- ppsci/arch/base.py
- ppsci/data/__init__.py
- ppsci/data/dataset/array_dataset.py
- ppsci/data/dataset/era5_dataset.py
- ppsci/data/dataset/vtu_dataset.py
- ppsci/data/process/batch_transform/__init__.py
- ppsci/data/process/transform/preprocess.py
- ppsci/solver/eval.py
- ppsci/solver/train.py
- ppsci/utils/__init__.py
- ppsci/utils/reader.py
- ppsci/visualize/plot.py
- ppsci/visualize/visualizer.py
- ppsci/visualize/vtu.py
APIs 
主要修改点：
1. 完善 train/eval.py 的代码逻辑
2. 优化 visualize 模块内部分函数的逻辑和 docstring
3. weight_dict 为 None 时默认转换为空字典，在该情况下 `xxxDataset.__getitem__` 中也返回空字典，删除 weight_dict 为 None 时的相关处理逻辑，简化代码。
> optimize code

- examples/cylinder/2d_unsteady/transformer_physx/train_enn.py
- examples/cylinder/2d_unsteady/transformer_physx/train_transformer.py
- examples/lorenz/train_enn.py
- examples/lorenz/train_transformer.py
- examples/rossler/train_enn.py
- examples/rossler/train_transformer.py
Others
Others
为Transformer相关案例增加argparse参数
> fix transformer examples

- docs/zh/examples/cylinder2d_unsteady_transformer_physx.md
- docs/zh/examples/lorenz.md
- docs/zh/examples/rossler.md
> fix docs in transformer examples

- ppsci/loss/integral.py
- ppsci/loss/l1.py
- ppsci/loss/l2.py
- ppsci/loss/mse.py
Bug fixes
APIs
Allow loss weight to be float or int data type
> Fix loss weight

- ppsci/solver/train.py
Bug fixes
APIs 
主要修改点：
1. 修复 train_LBFGS 里打印判断条件的bug
> fix print bug in train_LBFGS

- .github/ISSUE_TEMPLATE/1_bug-report.yml
- .github/ISSUE_TEMPLATE/2_feature-request.yml
- .github/ISSUE_TEMPLATE/3_build-installation-issue.yml
- .github/ISSUE_TEMPLATE/4_documentation-issue.yml
- .github/ISSUE_TEMPLATE/5_ask-a-question.yml
- .github/ISSUE_TEMPLATE/6_others.yml
Others 
Others 
主要修改点：
1. 更新 issue 模板
> update issue template

- test_tipc/README.MD
- test_tipc/benchmark_train.sh
Bug fixes
Docs
fix ${BENCHMARK_ROOT} env var
fit doc to the standard TIPC test procedure
> fix ${BENCHMARK_ROOT} env var

- ppsci/geometry/mesh.py
Bug fixes
APIs
主要修改点：
1. 完善加密采样代码
> update inflated sampling code for mesh

- README.md
- docs/index.md
- docs/zh/install_setup.md
- ppsci/metric/anomaly_coef.py
- ppsci/metric/l2_rel.py
- ppsci/metric/mae.py
- ppsci/metric/mse.py
- ppsci/metric/rmse.py
- ppsci/utils/expression.py
- ppsci/visualize/plot.py
Others
Docs
主要修改点：
1. 更新 release/1.0 分支的文档链接到 https://paddlescience-docs.readthedocs.io/zh/release-1.0/ 下
2. 完善 metric 模块 docstrings 中的公式
3. 修复部分 docstring 中出现冗余括号的问题
> Update doc for release/1.0

- ppsci/constraint/base.py
- ppsci/constraint/boundary_constraint.py
- ppsci/constraint/initial_constraint.py
- ppsci/constraint/integral_constraint.py
- ppsci/constraint/interior_constraint.py
- ppsci/constraint/periodic_constraint.py
- ppsci/constraint/supervised_constraint.py
- ppsci/loss/integral.py
- ppsci/loss/l1.py
- ppsci/loss/l2.py
- ppsci/loss/mse.py
- ppsci/validate/base.py
Bug fixes
APIs 
主要修改点：
1. 将只存在于 type hint 中的 module 通过 TYPE_CHECKING 分支导入
2. 为 initial_constraint 添加 `area` 数据处理的相关逻辑，修正其 `geom` 入参类型
3. 删除 periodic_constraint 不必要的 `f"`
4. 使用 `if xxx is not None` 代替 `if xxx`，避免隐式转换带来的问题
> Refine code

- docs/zh/api/loss.md
- docs/zh/api/metric.md
- examples/deephpms/burgers.py
- examples/deephpms/korteweg_de_vries.py
- examples/deephpms/kuramoto_sivashinsky.py
- examples/deephpms/navier_stokes.py
- examples/deephpms/schrodinger.py
- ppsci/loss/__init__.py
- ppsci/loss/func.py
- ppsci/metric/__init__.py
- ppsci/metric/func.py
Others
Others
add 5 DeepHPMs examples
add ppsci.loss.FunctionalLoss api
add ppsci.metric.FunctionalMetric api
update docs(zh)
> add DeepHPMs examples and FunctionalLoss&FunctionalMetric apis

- ppsci/geometry/mesh.py
Others 
Docs 
1. 细化 `Mesh` 模块的报错信息
> change ModuleNotFoundError to ImportError

- ppsci/data/dataset/era5_dataset.py
- ppsci/loss/integral.py
- ppsci/loss/l1.py
- ppsci/loss/l2.py
- ppsci/loss/mse.py
Bug fixes
APIs
修复ERA5Dataset数据集代码中的错误
> fix era5_dataset

- test_tipc/README.MD
- test_tipc/benchmark_train.sh
- test_tipc/configs/train_eular_beam/train_eular_beam.txt
Bug fixes
Others
fix tipc repo name bug
enlarge benchmark epoch of eualrbeam
> Tipc fix 0616

- README.md
- ppsci/solver/solver.py
APIs 
主要修改点：
1. 当当前设备只有CPU时，自动切换到CPU设备
> automatically switch device to cpu when only cpu is avaiable

- ppsci/geometry/geometry.py
- ppsci/geometry/geometry_3d.py
Others 
Others 
https://github.com/PaddlePaddle/PaddleScience/issues/376 case6
> [add sdf] cuboid

- README.md
- docs/index.md
Others 
Docs 
主要修改点：
1. 添加 acknowledgement
> add acknowledgement

- docs/zh/install_setup.md
- examples/euler_beam/euler_beam.py
- requirements.txt
- test_tipc/README.MD
Others 
Docs 
主要修改点：
1. 安装文档中添加 pybind11 的说明，并添加换行
2. requirements.txt 添加 seaborn 包
3. 格式化 test_tipc/README.MD
> refine install docs and some code

- ppsci/arch/activation.py
- ppsci/arch/mlp.py
New features
APIs
主要修改点：
1. 添加 `Stan` 激活函数
2. 微调 MLP 中 激活函数的初始化方式和代码块位置
> add Stan activation

- test_tipc/configs/train_2d_unsteady_continuous/train_2d_unsteady_continuous.txt
Bug fixes
Others
fix benchmark configs file
> fix tipc cylinder_2d fp32

- docker/Dockerfile
- docker/README.md
- docker/run.sh
- docs/zh/install_setup.md
Others
Others
https://github.com/PaddlePaddle/PaddleScience/issues/377
> add PaddleScience docker

- examples/aneurysm/aneurysm.py
- examples/bracket/bracket.py
- ppsci/geometry/mesh.py
- ppsci/loss/l2.py
- ppsci/metric/l2_rel.py
New features
APIs
主要修改点：
1. 添加 Aneurysm 案例
2. 修改 `Mesh` 中 `area` 字段的计算方式
其他：
1. 规范 `L2Rel` 的计算方式
> add aneurysm example and fix some bugs in Mesh

- examples/aneurysm/aneurysm.py
> update data path

- docker/run.sh
- docs/zh/install_setup.md
Others 
Others 
主要修改点：
1. 完善 docker 相关代码和文档
> refine code and docs for docker

- examples/deephpms/burgers.py
- examples/deephpms/korteweg_de_vries.py
- examples/deephpms/kuramoto_sivashinsky.py
- examples/deephpms/navier_stokes.py
- examples/deephpms/schrodinger.py
- examples/hpinns/functions.py
- ppsci/arch/activation.py
- ppsci/arch/base.py
- ppsci/data/dataset/array_dataset.py
- ppsci/data/process/transform/__init__.py
- ppsci/data/process/transform/preprocess.py
- ppsci/loss/func.py
- ppsci/metric/func.py
- ppsci/solver/solver.py
Others
1. add leaky relu activation
2. update type hints
3. let 'weight' be optional in array_dataset.py
4. add 'FunctionalTransform' Class
5. move judgement of use_amp before loading checkpoint
6. add parameter for 'FunctinalLoss' and 'FunctinalMetric'
> Add FunctionalTransform and update features

- docs/zh/examples/laplace2d.md
- examples/laplace/laplace2d.py
Bug fixes
Others
删除该案例中对边界条件点无用的criteria
> fix laplace 2d examples

- examples/tempoGAN/GAN.py
- examples/tempoGAN/functions.py
- examples/tempoGAN/tempoGAN.py
Others
Others
Add tempoGAN example
> Add tempoGAN example

- examples/tempoGAN/functions.py
- examples/tempoGAN/tempoGAN.py
- ppsci/arch/__init__.py
- ppsci/arch/gan.py
Others
Others
1. update tempoGAN example
2. move GAN to ppsci.arch
> update tempoGAN example

- docs/zh/examples/deeponet.md
Bug fixes
Docs
主要修改点：
1. 补充 DeepONet 案例文档
> update DeepONet doc

- docs/zh/examples/deeponet.md
Bug fixes
Docs
主要修改点：
1. 修复 DeepONet 文档章节和代码错位问题
> fix miss alignment and wrong order of DeepONet

- pyproject.toml
- setup.py
Others 
Others 
主要修改点：
1. 更新安装相关脚本中的版本号至 `1.1.0`
> update version to 1.1.0

- examples/aneurysm/aneurysm.py
- examples/bracket/bracket.py
Others 
Others 
主要修改点：
1. 将案例末尾评估 best_model 改为评估 latest，防止 epochs 太少导致没保存下 best_model
> Fix for ce

- docs/zh/examples/darcy2d.md
- ppsci/data/dataset/csv_dataset.py
- ppsci/data/dataset/vtu_dataset.py
Bug fixes
Docs
主要修改点：
1. 修复文档中 CSVDataset 和 VtuDataset 的两处错误
> fix typos in dataset desciption

- docs/zh/examples/deeponet.md
Others 
Docs 
主要修改点：
1. 更正 DeepONet 文档评估部分的代码区域
> update deeponet document(test=document_fix)

- docs/zh/examples/deeponet.md
- examples/aneurysm/aneurysm.py
- examples/bracket/bracket.py
- examples/operator_learning/deeponet.py
Others 
Docs 
主要修改点：
1. DeepONet 保存结果前创建目录
> Fix dir err

- docs/zh/examples/deeponet.md
Bug fixes
Docs
主要修改点：
1. 修复 DeepONet 文档中代码行数错位的问题
2. 更新 DeepONet AIStudio 项目运行连接
> fix line number and wrong aistudio url

- jointContribution/math.py
- ppsci/__init__.py
New features
APIs
1. add math module
2. add bassel i0/i0e/i1/i1e API
> add math module and some APIs

- examples/deephpms/navier_stokes.py
Others
Others
1. update evaluation config of navier_stokes file of deephpms example
> update ns example of deephpms

- ppsci/geometry/csg.py
- ppsci/geometry/geometry_1d.py
- ppsci/geometry/geometry_2d.py
- ppsci/geometry/geometry_3d.py
APIs
主要修改点：
1. 为 `Geometry.sdf_func` 添加必要检查
> update docstring and sanity check for geometries

- examples/ide/volterra_ide.py
Bug fixes
Others 
主要修改点：
1. 修复 volterra_ide 案例末尾没有将预测结果从Tensor转为numpy，导致某些版本的matplotlib可能会报错的问题
> convert predicted result fron Tensor to numpy for Volterra

- ppsci/equation/pde/navier_stokes.py
Bug fixes
APIs
Fix the NS equation, and delete the wrong density variable.
> fix viscosity of ns

- ppsci/geometry/geometry_2d.py
Bug fixes
APIs 
主要修改点：
1. 修复 Disk.sdf_func 函数中参数检查代码的BUG
> fix bug for sanity check in sdf_func of Disk

- examples/tempoGAN/functions.py
- examples/tempoGAN/tempoGAN.py
- ppsci/arch/gan.py
Others
Others
1. update ppsci.arch.gan
2. update tempoGAN example
3. todo: update linenum of doc
> update GAN network and tempoGAN example

- examples/tempoGAN/functions.py
- ppsci/arch/gan.py
Others
Others
1. update structure of gan.py
2. add data_range of skimage.metrics.structural_similarity in functions.py of tempoGAN example
> update structure of gan.py

- examples/deephpms/burgers.py
- examples/deephpms/korteweg_de_vries.py
- examples/deephpms/kuramoto_sivashinsky.py
- examples/deephpms/navier_stokes.py
- examples/deephpms/schrodinger.py
Others
Others
1. change metric of evaluation of all examples
> update DeepHPMs examples

- examples/deephpms/burgers.py
- examples/deephpms/korteweg_de_vries.py
- examples/deephpms/kuramoto_sivashinsky.py
- examples/deephpms/navier_stokes.py
Others
Others
1. delete functional metric because of updating of l2 metric.
> update DeepHPMs' l2 metrics

- ppsci/arch/__init__.py
- ppsci/arch/afno.py
- ppsci/arch/deeponet.py
- ppsci/arch/embedding_koopman.py
- ppsci/arch/gan.py
- ppsci/arch/physx_transformer.py
- ppsci/solver/printer.py
Bug fixes
APIs 
主要修改点：
1. 修改相关案例代码，适配修改后的`output_transform`
其他：
1. 完善`printer.py`的type hint
2. API 文档添加基类 Arch
> Fix code in examples for change of output_transform

- docs/zh/examples/hpinns.md
Others
Docs
1. update linenums of hPINNs doc(zh)
> update hPINNs doc(zh)

- docs/zh/examples/tempoGAN.md
Others
Docs
1. update linenum of tempoGAN doc(zh)
> update tempoGAN doc(zh)

- ppsci/geometry/geometry_2d.py
Bug fixes
APIs
1. fix code of sdf_func in ppsc.geom.Rectangle
> Fix code of sdf_func in Rectangle of geom 2d

- examples/aneurysm/aneurysm_flow.py
- examples/pipe/poiseuille_flow.py
Bug fixes
Others 
主要修改点：
1. 修复`examples/aneurysm/aneurysm_flow.py`和`examples/pipe/poiseuille_flow.py`导致运行报错的BUG
> fix for aneurysm_flow and poiseuille flow

- ppsci/arch/activation.py
Bug fixes
APIs 
主要修改点：
1. 修复 `Siren` 激活函数BUG
> fix siren activation

- docs/zh/api/loss.md
- ppsci/loss/mtl/__init__.py
- ppsci/loss/mtl/base.py
- ppsci/loss/mtl/pcgrad.py
- ppsci/solver/solver.py
- ppsci/solver/train.py
> [Feature]add multi-task learning module and a method "PCGrad"

- ppsci/solver/printer.py
- ppsci/solver/solver.py
- ppsci/solver/train.py
- ppsci/utils/misc.py
New features
Others
1. add a function to plot train losses
2. usage like,
epoch loss of deeponet's constraint with smooth_step=1, use_semilogy=False:
with smooth_step=1000, use_semilogy=False:
with smooth_step=1, use_semilogy=True:
with smooth_step=1000, use_semilogy=True:
> add func of plotting losses

- docs/zh/api/experimental.md
Others 
Docs 
主要修改点：
1. 添加 experimental 模块的文档
> [Doc]add document of experimental module

- ppsci/experimental/math.py
Others
Docs
1. add docstring of APIs.
> [Doc]Add docstring of ppsci.experimental.math

- examples/hpinns/functions.py
Others
Others
1. paddlepaddle cannot automatically convert the index of slice to int type, update the example to adapt to it.
> Update hPINNs example to adapt to paddlepaddle

- jointContribution/Deep-Spatio-Temporal/README.md
- jointContribution/Deep-Spatio-Temporal/getNRELdata.py
- jointContribution/Deep-Spatio-Temporal/src/datamgr.py
- jointContribution/Deep-Spatio-Temporal/src/model.py
- jointContribution/Deep-Spatio-Temporal/src/trainer.py
- jointContribution/Deep-Spatio-Temporal/src/utils.py
- jointContribution/Deep-Spatio-Temporal/train.py
Others
Others
https://github.com/PaddlePaddle/Paddle/issues/55663#paddlepaddle14
Test Loss 信息
| Test Loss | torch | paddle |
| - | - | - |
| wind_power | 1.5525 | 1.5549 |
| wind_speed | 0.2646 | 0.2522 |
wind_power 运行
torch
paddle
wind_speed 运行
torch
paddle
> PaddleScience 领域经典论文复现 Deep Spatio-Temporal 

- docs/zh/install_setup.md
- examples/bracket/bracket.py
- examples/laplace/laplace2d.py
Others 
Docs 
1. 在PyMesh 安装说明之前，添加cmake的安装说明
> [Doc] add cmake installation as preliminary

- ppsci/equation/pde/navier_stokes.py
> fix comment and doc

- docs/zh/examples/labelfree_DNN_surrogate.md
- ppsci/equation/pde/navier_stokes.py
> Docfix surrogate

- ppsci/probability/__init__.py
- ppsci/probability/hmc.py
- test/probability/test_hmc.py
New features
APIs
Add HamiltonianMonteCarlo API
相关 Issues :https://github.com/PaddlePaddle/PaddleScience/issues/450
> 【快乐开源】添加 HamiltonianMonteCarlo API

- examples/deephpms/burgers.py
- examples/deephpms/korteweg_de_vries.py
- examples/deephpms/kuramoto_sivashinsky.py
- examples/deephpms/navier_stokes.py
- examples/deephpms/schrodinger.py
> [Docs] fix incorrect validator param in DeepHPMs example

- docs/zh/examples/hpinns.md
- examples/hpinns/holography.py
- ppsci/solver/solver.py
Bug fixes
Others 
1. 修复 solver.py 内没有对 equation 判空的逻辑，导致数据驱动的案例可能运行报错
2. 完善 hPINNs 文档的下载命令
> [Fix] Fix run failure when equation is empty in data-driven case

- examples/cylinder/2d_unsteady/transformer_physx/train_enn.py
- examples/cylinder/2d_unsteady/transformer_physx/train_transformer.py
- examples/lorenz/train_enn.py
- examples/lorenz/train_transformer.py
- examples/rossler/train_enn.py
- examples/rossler/train_transformer.py
- ppsci/constraint/boundary_constraint.py
- ppsci/constraint/initial_constraint.py
- ppsci/constraint/integral_constraint.py
- ppsci/constraint/interior_constraint.py
- ppsci/constraint/periodic_constraint.py
- ppsci/equation/pde/navier_stokes.py
- ppsci/solver/solver.py
- ppsci/utils/symbolic.py
- test/equation/test_viv.py
Bug fixes
APIs
1. 修复 N-S 方程对于 nu 的处理问题
2. 修复 symbolic 调试时的路径名字，以及保存计算图之前的创建文件夹
3. symbolic 未匹配到模型时添加报错提示
其他：
1. 删除几个案例中不必要的对 model 外的中括号
> [Fix] fix for poiseuille_flow and symbolic

- README.md
- docs/index.md
- docs/requirements.txt
- docs/zh/install_setup.md
- mkdocs.yml
- ppsci/equation/pde/biharmonic.py
- ppsci/equation/pde/laplace.py
- ppsci/equation/pde/linear_elasticity.py
- ppsci/equation/pde/navier_stokes.py
- ppsci/equation/pde/normal_dot_vec.py
- ppsci/equation/pde/poisson.py
- ppsci/utils/initializer.py
Others
Docs
1. 主页添加 "最近更新" 章节
2. 通过章节引用，减少文档的重复内容，优化首页文档结构
3. 修复方程模块的 `detach_keys` 文档中缺少空格的问题
4. 文档末尾添加历史记录功能
5. 修复 `_no_grad_trunc_normal_` 默认参数 `a=2.0` 的 BUG，应该是 `-2.0`
> [Doc&Fix] update front page and fix docstring in equation

- docs/zh/examples/cylinder2d_unsteady_transformer_physx.md
- docs/zh/examples/lorenz.md
- docs/zh/examples/rossler.md
- ppsci/data/dataset/trphysx_dataset.py
Others
Docs
修改transformer physx三个案例的数据集下载地址
> fix doc for transformer physx

- docs/zh/examples/shock_wave.md
- examples/shock_wave/lhs.py
- examples/shock_wave/shock_wave.py
Others 
Others 
1. 修复 ShockWave 案例类型未转换导致运行报错的问题
2. 添加 ShockWave 在 AIStudio 上的项目链接
> [Fix] Fix shockwave code and add aistudio url

- docs/zh/examples/lorenz.md
- docs/zh/examples/rossler.md
Others
Docs
1. 修改Lorenz案例文档的章节号
> Fix chapter number

- docs/zh/examples/labelfree_DNN_surrogate.md
Doc fixes
Docs
fix py linenums
> surrogate doc fix

- examples/deepcfd/deepcfd.py
- ppsci/autodiff/ad.py
- ppsci/constraint/integral_constraint.py
- ppsci/data/dataset/era5_dataset.py
- ppsci/data/dataset/vtu_dataset.py
- ppsci/data/process/transform/preprocess.py
- ppsci/equation/pde/base.py
- ppsci/geometry/mesh.py
- ppsci/loss/mtl/agda.py
- ppsci/loss/mtl/pcgrad.py
- ppsci/probability/hmc.py
- ppsci/solver/eval.py
- ppsci/solver/solver.py
- ppsci/utils/checker.py
- ppsci/utils/misc.py
- ppsci/utils/symbolic.py
- ppsci/validate/base.py
- setup.py
Others
Others 
1. 修正多处 type hint 问题
2. setup.py 依赖项改为从 `requirements.txt` 中读取，避免维护两份依赖文本
> [Fix] Correct type hint and optimize setup.py

- examples/rossler/train_enn.py
Others
Others
修改rossler案例的随机种子
> modify random seed

- docs/zh/api/data/process/transform.md
Others
Docs
Add 'FunctionalTransform' in doc
> [Doc]Add 'FunctionalTransform'(test=document_fix)

- docs/zh/examples/bracket.md
- examples/bracket/conf/bracket.yaml
- ppsci/utils/misc.py
Others 
Others 
修复 bracket.md 中的部分代码块错位以及完善 `cartesian_product` 的 docstring
> [Fix] Fix bracket doc

- ppsci/arch/base.py
- ppsci/arch/model_list.py
- ppsci/solver/solver.py
Bug fixes
Others 
1. 为 `ModelList` 和 `DataParallel` 添加 `input_keys`, `output_keys` 属性，避免在 `symbolic.py` 等文件中，访问这类属性时报错
> [Fix] add input/output_keys for ModelList and DataParallel model

- requirements.txt
Others
Others
update required version of numpy
> [Fix]Update required version of numpy(test=document_fix)

- ppsci/data/process/transform/preprocess.py
Bug fixes
Others
fix transfer `None` as parameter
> [Fix]weight_dict of FunctionalTransform

- README.md
- docs/index.md
- docs/stylesheets/extra.css
Others 
Docs 
1. 优化主页并添加社区贡献者列表
> [Doc] Update index and README

- README.md
- docs/index.md
- docs/stylesheets/extra.css
Bug fixes
Docs
1. 移动css至index.md解决在extra.css内无法渲染的问题
> [Fix] Move css into index.md

- README.md
- docs/index.md
> [Doc] update contributor

- docs/zh/examples/labelfree_DNN_surrogate.md
- examples/pipe/conf/poiseuille_flow.yaml
- examples/pipe/poiseuille_flow.py
Others 
Others 
10 labelfree_DNN_surrogate
> 【hydra No.10】labelfree_DNN_surrogate

- docs/zh/examples/darcy2d.md
- examples/darcy/conf/darcy2d.yaml
- examples/darcy/darcy2d.py
> 【hydra No.9】darcy2d

- ppsci/data/dataset/__init__.py
- ppsci/data/process/transform/__init__.py
- ppsci/geometry/geometry.py
- ppsci/geometry/mesh.py
- ppsci/geometry/pointcloud.py
- ppsci/utils/reader.py
Others 
Docs 
1. 修复代码中剩余的少量 typo
2. 给 `Mesh.translate/scale` 方法添加 docstring
> [Refine] Fix more typos

- docs/zh/examples/tempoGAN.md
- examples/tempoGAN/conf/tempogan.yaml
- examples/tempoGAN/tempoGAN.py
Others
Others
1. Add eval function of tempoGAN example
2. Update doc of tempoGAN example
> [Update] Add eval function of tempoGAN example and update doc

- ppsci/utils/misc.py
Others
Others
1. Apply "log" both in x and y axis
Difference like (before/after):
> [Update]Apply "log" both in x&y axis

- docs/zh/examples/deephpms.md
- examples/deephpms/burgers.py
- examples/deephpms/conf/burgers.yaml
- examples/deephpms/conf/korteweg_de_vries.yaml
- examples/deephpms/conf/kuramoto_sivashinsky.yaml
- examples/deephpms/conf/navier_stokes.yaml
- examples/deephpms/conf/schrodinger.yaml
- examples/deephpms/korteweg_de_vries.py
- examples/deephpms/kuramoto_sivashinsky.py
- examples/deephpms/navier_stokes.py
- examples/deephpms/plotting.py
- examples/deephpms/schrodinger.py
Others
Others
1. Add eval function of deephpms example
2. Add plotting file of deephpms example
3. Update doc of deephpms example
> [Update]Add eval function of deephpms examples and update doc

- docs/zh/examples/hpinns.md
- examples/hpinns/functions.py
Others
Others
Update hpinns docs
> [Update]Update hpinns docs

- examples/cylinder/2d_unsteady/transformer_physx/conf/enn.yaml
- examples/lorenz/conf/enn.yaml
- examples/rossler/conf/enn.yaml
Bug fixes
Others
修改transformer三个案例的enn配置文件中的输出路径
> update output dir

- README.md
- docs/zh/examples/aneurysm.md
- docs/zh/examples/cfdgcn.md
- docs/zh/examples/cylinder2d_unsteady.md
- docs/zh/examples/laplace2d.md
- docs/zh/examples/shock_wave.md
- docs/zh/user_guide.md
- examples/cylinder/2d_unsteady/conf/cylinder2d_unsteady_Re100.yaml
- examples/cylinder/2d_unsteady/cylinder2d_unsteady_Re100.py
- examples/shock_wave/shock_wave.py
Others 
Docs 
1. 完善 CFD-GCN 文档
2. 修复 cylinder2d_unsteady_Re100 文档的部分描述错误
3. 修复 shock_wave 中的不合理代码
> [Fix] Refine code and document

- docs/zh/examples/ldc2d_steady.md
- docs/zh/examples/ldc2d_unsteady.md
- ppsci/solver/solver.py
- test_tipc/configs/train_2d_unsteady_continuous/2d_unsteady_continuous_train_infer_python.txt
Others 
Docs 
1. 添加 ldc2d_steady 和 ldc2d_unsteady 两个案例的评估命令
2. 添加对非 develop 版 paddle 的警告，提示暂时推荐使用 develop 版 paddle
3. 更新 TIPC 运行重载命令为hydra语法
> [Doc] Add pretrain and version warning

- docs/zh/examples/ldc2d_steady.md
- docs/zh/examples/ldc2d_unsteady.md
Others 
Docs 
1. 添加 ldc2d_steady 和 ldc2d_unsteady 的预训练模型下载地址和评估指标
> [Doc] update pretrained model dowload link

- README.md
- docs/index.md
- docs/zh/examples/shock_wave.md
- examples/aneurysm/aneurysm.py
- examples/shock_wave/shock_wave.py
- mkdocs.yml
- pyproject.toml
- setup.py
Others 
Docs 
1. 按字典序排列案例
2. 文档描述中删除对 python3.7 的支持
3. 删除 aneurysm.py 的两行无用代码
4. 优化 shock wave 代码与文档
> [Doc] sort examples by lexicographic order

- ppsci/equation/pde/linear_elasticity.py
Others
APIs
Fix linear_elasticity equation
> [Fix]Fix linear_elasticity equation

- docs/zh/examples/cylinder2d_unsteady_transformer_physx.md
- docs/zh/examples/fourcastnet.md
- docs/zh/examples/lorenz.md
- docs/zh/examples/rossler.md
- examples/fourcastnet/conf/fourcastnet_finetune.yaml
- examples/fourcastnet/conf/fourcastnet_precip.yaml
- examples/fourcastnet/conf/fourcastnet_pretrain.yaml
- examples/fourcastnet/train_finetune.py
- examples/fourcastnet/train_precip.py
- examples/fourcastnet/train_pretrain.py
Others
将FourCastNet案例中的代码修改为使用hydra进行配置
TODO：
更新案例文档
> modify fourcast to hydra style

- docs/zh/examples/deephpms.md
Others
Docs
Update deephpms doc
> [Docs]Update deephpms doc(test=document_fix)

- docs/stylesheets/extra.css
- pyproject.toml
Others 
Others 
1. 更改 css 样式，更新 pyproject.toml
> [Fix] Update css and pyproject.toml

- README.md
- docs/index.md
- docs/zh/examples/pirbn.md
> PIRBN_docfix

- ppsci/utils/misc.py
Others 
Docs 
1. Example -> Examples
> [Fix] fix example in RankZeroOnly

- docs/zh/examples/cylinder2d_unsteady_transformer_physx.md
- docs/zh/examples/lorenz.md
- docs/zh/examples/rossler.md
Ohters
Docs
下载Transformer Physx 案例数据集时，增加存储路径
> fix transformer physx doc

- docs/zh/examples/tempoGAN.md
- examples/tempoGAN/functions.py
- examples/tempoGAN/tempoGAN.py
Others
Others
1. fix output dir error of tempoGAN
2. add log of loading datasets
3. update doc
> [Fix]Fix output dir error of tempoGAN and update doc

- README.md
- ppsci/solver/printer.py
- ppsci/solver/solver.py
Others 
Others 
1. 安装教程添加 paddle 安装验证命令
2. 根据 #652 修改，添加 benchmark 功能，环境变量中存在 `BENCHMARK_ROOT` 时训练信息末尾添加显存占用情况。如下所示
```
[2023/11/22 03:26:51] ppsci INFO: [Train][Epoch 33/100000][Avg] loss: 1.52524, Sup: 1.52524
[2023/11/22 03:26:51] ppsci MESSAGE: Finish saving checkpoint to outputs_VIV/2023-11-22/03-26-49/checkpoints/latest
[2023/11/22 03:26:51] ppsci INFO: [Train][Epoch 34/100000][Iter: 1/1] lr: 0.00100, loss: 1.36563, Sup: 1.36563, batch_cost: 0.02912s, reader_cost: 0.00236s, ips: 3434.20769 samples/s, eta: 0:48:30, max_mem_reserved: 1380096 B, max_mem_allocated: 1232896 B
[2023/11/22 03:26:51] ppsci INFO: [Train][Epoch 34/100000][Avg] loss: 1.36563, Sup: 1.36563
[2023/11/22 03:26:51] ppsci MESSAGE: Finish saving checkpoint to outputs_VIV/2023-11-22/03-26-49/checkpoints/latest …
```
> [Doc&benchmark] Add paddle install validation and benchmark flag

- README.md
- docs/index.md
- docs/zh/examples/biharmonic2d.md
- docs/zh/examples/deephpms.md
- examples/biharmonic2d/biharmonic2d.py
- examples/biharmonic2d/conf/biharmonic2d.yaml
- mkdocs.yml
- ppsci/equation/pde/biharmonic.py
- ppsci/solver/solver.py
- ppsci/utils/misc.py
Others
Others
1. add biharmonic2d example
2. add biharmonic2d doc
3. modify biharmonic equation api
4. modify deephpms doc
5. delate some docstring of ppsci.utils.misc.py
6. modify solver.predict to support autodiff
> [Add&Modify]Add biharmonic2d example and some other modifies

- docs/zh/examples/phylstm.md
Others 
Docs 
1. 删除 phylstm 文档冗余内容
> [Fix] Remove redundant content

- ppsci/solver/solver.py
Others 
Others 
1. 修复 Solver.predict num_pad>0时对numpy数据padding错误调用paddle接口的问题
> [Fix] Fix for padding numpy input in predict

- README.md
- docs/index.md
- docs/zh/examples/phylstm.md
Others 
Others 
1. 安装教程添加 windows 安装说明，避免安装失败。
2. 删除文档一处多余内容
> [Fix] Fix windows install failure

- docs/zh/examples/cylinder2d_unsteady_transformer_physx.md
- docs/zh/examples/lorenz.md
- docs/zh/examples/phylstm.md
- docs/zh/examples/rossler.md
- examples/cylinder/2d_unsteady/transformer_physx/conf/transformer.yaml
- examples/lorenz/conf/transformer.yaml
- examples/rossler/conf/transformer.yaml
- ppsci/utils/misc.py
Bug fixes
Others 
1. 修复 all_gather 给定非连续 Tensor 的时候返回的通讯结果不正确的问题
> [Fix] Fix all gather with non-contiguous Tensor

- docs/requirements.txt
- docs/zh/user_guide.md
- examples/amgnet/amgnet_airfoil.py
- examples/amgnet/amgnet_cylinder.py
- ppsci/solver/solver.py
- ppsci/utils/logger.py
- ppsci/utils/save_load.py
Bug fixes
Docs 
1. 更正 `logger.scaler` 中调用 vdl 错误的参数位置
2. 添加 metric 记录在 vdl 时的关键字前缀
3. 完善使用指南文档，并增加 VisualDL 相关内容
> [Fix&Doc] Fix vdl

- .github/ISSUE_TEMPLATE/3_build-installation-issue.yml
- .github/ISSUE_TEMPLATE/4_documentation-issue.yml
- .github/ISSUE_TEMPLATE/5_ask-a-question.yml
- README.md
- docs/zh/examples/aneurysm.md
- docs/zh/examples/bracket.md
- docs/zh/reproduction.md
- jointContribution/PINO/rfcs/PINO.md
- jointContribution/graphGalerkin/rfcs/graphGalerkin.md
- ppsci/utils/checker.py
- pyproject.toml
- setup.py
Others 
Others 
1. 发布 1.2.0 版本，替换所有 1.0.0 和 latest 字段
> [Release 1.2.0] Change version information from 1.0.0/latest to 1.2.0

- ppsci/solver/solver.py
Others 
APIs 
1. 修复 DDP + `ModelList` 下构建符号计算报错问题，将 DataParallel 包装对象改为 ModelList 下的每个 model，而非 ModelList 本身
> [Fix] Fix DDP wrapper for symbolic computation

- .gitignore
- ppsci/constraint/interior_constraint.py
- ppsci/utils/symbolic.py
- test/utils/test_symbolic.py
Bug fixes
Others 
1. 添加 `_version.py` 到 `.gitignore` 中
2. symbolic 模块适配 sdf 函数，并添加单测
> [Fix] Add _version.py to .gitignore and refine symbolic module

- ppsci/loss/mtl/agda.py
- ppsci/loss/mtl/relobralo.py
Others 
Docs 
1. Fix docstring of AGDA and add assert for ReloBRalo
> [Fix] Fix docstring of AGDA and add assert for ReloBRalo

- .pre-commit-config.yaml
Others
Others
In `.pre-commit-config.yaml`, add args `--autofix` for pretty-format-json to autofix `.json` file.
> [PreCommit] Update pretty-format-json args

- ppsci/loss/l1.py
Others
Docs
增加了描述和示例代码，看看这样改是否合适，可以的话其他的loss我也按这样来改吧
> 【PPSCI Doc No.76】

- docs/index.md
- ppsci/data/process/batch_transform/__init__.py
> [Doc] update docs

- docs/zh/examples/topopt.md
- examples/topopt/topopt.py
Others
Others
Add logger initialation of topopt example
> [Fix]Add logger initialation of topopt example

- ppsci/data/dataset/era5_dataset.py
Others 
Docs 
https://github.com/PaddlePaddle/PaddleScience/issues/686 No. 8
> 【PPSCI Doc No.8】ppsci.data.dataset.ERA5SampledDataset

- examples/euler_beam/conf/euler_beam.yaml
- examples/euler_beam/euler_beam.py
- ppsci/solver/eval.py
- ppsci/solver/train.py
Others 
Docs 
1. euler_beam 适配hydra
2. tain.py/eval.py 删除注释的 profiler代码，并移动部分代码位置
> [Hydra] Change euler_beam code to hydra style

- ppsci/data/process/transform/preprocess.py
Others 
Docs 
https://github.com/PaddlePaddle/PaddleScience/issues/686 No. 2-7
> 【PPSCI Doc No.2-7】ppsci.data.process.transform

- ppsci/data/__init__.py
Performance optimization
Others 
1. 添加禁用 auto collation 的读取方式，提升某些场景下的数据读取速度
> [Enh] add auto collation for speed up data loading

- docs/zh/examples/deepcfd.md
Others 
Docs 
1. 修复 DeepCFD 文档图片链接失效问题
> [Doc] Fix deepcfd F-18 image url(test=document_fix)

- test_tipc/configs/train_eular_beam/eular_beam_train_infer_python.txt
Others 
Others 
1. 修复 euler_beam TIPC 运行参数
> [Fix] Fix euler_beam in benchmark

- docs/zh/examples/cfdgcn.md
- ppsci/arch/cfdgcn.py
Others 
Docs 
CDFGCN 案例文档
- https://github.com/PaddlePaddle/PaddleScience/pull/609#event-11204667530
- https://github.com/PaddlePaddle/PaddleScience/issues/441
> 【快乐开源】迁移 CFDGCN 案例至 PaddleScience

- ppsci/solver/printer.py
Others 
Others 
1. 根据测试规范，恢复 ips 的单位字符串
> [Fix] Restore unit for ips

- ppsci/metric/func.py
- ppsci/metric/l2_rel.py
- ppsci/metric/mae.py
- ppsci/metric/mse.py
- ppsci/metric/rmse.py
- ppsci/solver/solver.py
Others
Docs
PPSCI Doc No.86-92
> 【PPSCI Doc No.86-92】

- ppsci/solver/solver.py
- ppsci/solver/train.py
- test_tipc/README.MD
- test_tipc/benchmark_train.sh
- test_tipc/configs/train_2d_unsteady_continuous/2d_unsteady_continuous_train_infer_python.txt
- test_tipc/configs/train_eular_beam/eular_beam_train_infer_python.txt
- test_tipc/prepare.sh
Bug fixes
Others
Fix TIPC benchmark tests for Performance
> Tipc fix 1226

- docs/zh/examples/euler_beam.md
- examples/euler_beam/euler_beam.py
- mkdocs.yml
> add euler beam doc

- docs/zh/api/experimental.md
- ppsci/experimental/__init__.py
- ppsci/experimental/math_module.py
- test/experimental/test_trapezoid_integrate.py
New features
APIs
1. add trapezoid integrate
2. add its test
> [Fea]Add trapezoid integrate

- README.md
- docs/index.md
- docs/zh/install_setup.md
- mkdocs.yml
- ppsci/arch/uscnn.py
- ppsci/experimental/math_module.py
- ppsci/solver/solver.py
Others 
Others 
1. 更新在 Release 1.2.1 中的相关链接地址
> [Release] Update for release/1.2.1

- README.md
- docs/index.md
- ppsci/visualize/plot.py
Others 
Docs 
1. 添加 DeePMD-kit paddle 后端支持的相关说明
2. plot2d 可视化函数中plot回退到scatter，因为plot要求输入数据有序。改用scatter并调整点的大小和背景网格灰度
3. 更新首页文档的几处
> [Doc] Add DeePMD-kit description

- ppsci/equation/pde/heat_exchanger.py
Bug fixes 
APIs
1. 修复 heat_exchanger 方程里的错误
> [Fix] Fix heat_exchanger equation

- examples/pipe/conf/poiseuille_flow.yaml
- examples/pipe/poiseuille_flow.py
New features
Others
Complete unfinished Hydra Project
> Poiseuille Flow Fix

- pyproject.toml
Others 
Others 
1. 更新python版本要求和scm工具
> [Fix] Fix scm tools

- docs/zh/install_setup.md
- examples/quick_start/case2.py
- ppsci/autodiff/ad.py
- ppsci/utils/symbolic.py
Others 
Docs 
1. 更新个别函数的docstring以及docker安装的提示警告
> [Fix] Fix docstrings and note

- ppsci/utils/misc.py
> 【PPSCI Doc No.103】

- ppsci/utils/save_load.py
Others
Docs
No.104-105
link #686
> 【PPSCI Doc No.104-105】

- setup.py
Bug fixes
Others 
1. pip 安装时调用 setup.py 中的 `get_readme` 函数读取文档内容，在windows机器上有概率触发gbk相关报错，因此指定读取编码为`utf-8`防止报错
> [Fix] Fix install encoding problem

- docs/zh/examples/tempoGAN.md
- docs/zh/examples/topopt.md
- examples/tempoGAN/tempoGAN.py
- examples/topopt/functions.py
- examples/topopt/topopt.py
- examples/topopt/topoptmodel.py
Bug fixes
Others
1. fix data transform error
2. fix model name of hint
3. add "auto_collation" for example topopt and tempoGAN
> [Fix]fix data transform error

- docs/zh/examples/tempoGAN.md
- docs/zh/examples/topopt.md
- examples/tempoGAN/tempoGAN.py
- examples/topopt/functions.py
- examples/topopt/topopt.py
- examples/topopt/topoptmodel.py
Reverts PaddlePaddle/PaddleScience#779
> Revert "[Fix]fix data transform error"

- examples/topopt/functions.py
- examples/topopt/topoptmodel.py
- ppsci/data/__init__.py
Others
APIs
1. set 'auto_collation' false when using data transform
2. fix data transform error of topopt example
> [Update]update setting of 'auto_collation' and fix errors

- examples/yinglong/README.md
Others
Docs 
添加依赖安装代码，修改部分文字位置
> [Doc] Add requirements for yinglong model

- docker/Dockerfile
- docs/zh/install_setup.md
- examples/aneurysm/aneurysm.py
Others 
Others 
1. pymesh.tar.xz 安装包更新为 python3.9 编译内容，适配 dockerfile 默认安装的 python3.9
2. 完善 aneurysm 部分代码
> [Docker] Update dockerfile & refine aneurysm

- examples/epnn/conf/epnn.yaml
- examples/epnn/epnn.py
- examples/epnn/functions.py
Others 
Others 
EPNN 训练数据生成时使用随机排列生成方式改回 paddle 实现，避免收敛精度问题
> [Fix[ Fix epnn accuracy

- docs/zh/examples/euler_beam.md
- examples/euler_beam/conf/euler_beam.yaml
- examples/euler_beam/euler_beam.py
Others
Others
- https://github.com/PaddlePaddle/PaddleScience/issues/788
> 【PPSCI Export&Infer No.3】euler_beam

- docs/zh/api/arch.md
- ppsci/arch/__init__.py
- ppsci/arch/mlp.py
APIs 
1. 参考论文 [Understanding and mitigating gradient pathologies in physics-informed
neural networks](https://arxiv.org/pdf/2001.04536.pdf)，添加`ModifiedMLP`网络结构
> [Fea] Add ModifiedMLP

- docs/zh/examples/lorenz.md
- examples/lorenz/conf/transformer.yaml
- examples/lorenz/train_transformer.py
Others
Others
- #788 
- 这个模型开启 `ir_optim: true` 会导出的特别慢。
> 【PPSCI Export&Infer No.5】lorenz

- docs/zh/examples/rossler.md
- examples/rossler/conf/transformer.yaml
- examples/rossler/train_transformer.py
Others
Others
- https://github.com/PaddlePaddle/PaddleScience/issues/788
> 【PPSCI Export&Infer No.6】rossler

- docs/zh/examples/volterra_ide.md
- examples/ide/conf/volterra_ide.yaml
- examples/ide/volterra_ide.py
Others
Others
- https://github.com/PaddlePaddle/PaddleScience/issues/788
> 【PPSCI Export&Infer No.7】 volterra_ide

- docs/zh/examples/viv.md
- docs/zh/user_guide.md
- examples/fsi/conf/viv.yaml
- examples/fsi/viv.py
- ppsci/solver/printer.py
- ppsci/solver/solver.py
- ppsci/utils/logger.py
- ppsci/utils/symbolic.py
New features
APIs 
1. 添加 `TensorBoardX` 的支持，以及使用说明
2. 将 vdl、wandb、tensorboardX 所在的章节合并为 1.7 实验过程可视化
> [Fea] Support tensorboardX and add corresponding guidance

- docs/zh/examples/laplace2d.md
- examples/laplace/conf/laplace2d.yaml
- examples/laplace/laplace2d.py
Others 
Docs 
1. 删除laplace2d案例中固定随机种子和创建输出目录的代码(该部分功能由callback完成)，更新随机种子为2024，并更新对应文档。
> [Fix] Remove seed and directory code to slim laplace2d exmaples

- ppsci/solver/solver.py
- ppsci/utils/logger.py
- ppsci/utils/symbolic.py
- ppsci/utils/writer.py
- ppsci/visualize/plot.py
- ppsci/visualize/vtu.py
Bug fixes 
APIs 
1. 创建文件夹前需判断文件夹路径是否是合法路径，否则遇到`''`之类的空字符串路径会报错
> [Fix] Check if is directory befoe mkdirs

- jointContribution/XPINNs/XPINN_2D_PoissonsEqn.py
Bug fixes
Others 
修复绘图错误，下面左图为修复前结果，右图为修复后结果
原论文图片
> fix plotting error in XPINN example

- ppsci/equation/pde/base.py
Others
Docs
补全了以下API文档，添加了样例代码：
- ppsci.equation.PDE.add_equation
- ppsci.equation.PDE.create_function
- ppsci.equation.PDE.create_symbols
> 【PPSCI Doc No.35-37】

- docs/zh/api/utils/ema.md
Others 
Docs 
1. 补充缺少的`ema.md`文件
> [Doc] Add missing ema document file

- docker/Dockerfile
- docker/run.sh
- docs/zh/install_setup.md
- examples/NLS-MB/conf/NLS-MB_rogue_wave.yaml
- examples/NLS-MB/conf/NLS-MB_soliton.yaml
New features
Others 
1. 添加直接从 dockerhub 拉取镜像的方式以创建运行环境，并修改文档中的相关内容。
> [Docker] Add docker image

- examples/yinglong/README.md
> Update YingLong1 README.md

- .gitmodules
- competition/README.md
1. add competition directory
2. add IJCAI_2024 submodule
> [Add]Add competition&IJCAI_2024 submodule

- competition/README.md
1. update competition description
2. fix website
> [Update]update competition description

- docs/zh/examples/heat_exchanger.md
- examples/heat_exchanger/conf/heat_exchanger.yaml
- examples/heat_exchanger/heat_exchanger.py
> 【PPSCI Export&Infer No.30】heat_exchanger

- docs/zh/examples/control_arm.md
- examples/control_arm/conf/forward_analysis.yaml
- examples/control_arm/conf/inverse_parameter.yaml
- examples/control_arm/forward_analysis.py
- examples/control_arm/inverse_parameter.py
Others
Others
- [](https://github.com/PaddlePaddle/PaddleScience/issues/788#top) #788
> 【PPSCI Export&Infer No.26-27】

- docs/zh/examples/phycrnet.md
- examples/phycrnet/functions.py
- ppsci/arch/phycrnet.py
- ppsci/utils/download.py
Bug fixes
Others 
1. 修复phycrnet参数载入名称不正确，eval报错，文档格式问题，并重新上传了正确的pdparams
> [Fix] Fix phycrnet bug

- docs/zh/examples/cylinder2d_unsteady_transformer_physx.md
Others 
Docs
1. 删除重复的"模型推理命令"选项卡
> [Doc] Fix doc of cylinder2d_unsteady_transformer_physx

- docs/zh/user_guide.md
- ppsci/solver/solver.py
- requirements.txt
Bug fixes
APIs 
1. Solver 中的参数统一使用 self.xxx，而不是同名入参。
> [Fix] Fix output_dir for visualDL and tensorboardX

- docs/zh/api/equation.md
- examples/allen_cahn/allen_cahn_causal.py
- examples/allen_cahn/allen_cahn_default.py
- examples/allen_cahn/allen_cahn_piratenet.py
- examples/allen_cahn/allen_cahn_plain.py
- ppsci/equation/pde/allen_cahn.py
- test/equation/test_detach.py
Bug fixes
Docs 
1. 修复 AllenCahn 方程的docstring描述错误，更正相关代码
> [Fix] Correct desciprtion of epsilon of AllenCahn equation

- examples/cylinder/2d_unsteady/transformer_physx/train_transformer.py
Bug fixes
Others
修复cylinder transformer案例导出和静态图推理问题
> fix export and infer

- .github/workflows/publish.yml
Others 
Others 
1. 对develop分支，按照commit的粒度自动发布pip whl包到pypi上
> [PIP] Auto build and upload develop pip whl to pypi when receive new commiting

- .github/workflows/publish.yml
Others 
Others 
1. 修复 publish.yml 文件中 3.10 可能被解析为3.1的问题
> [PIP] Fix for 3.10

- docs/index.md
- docs/zh/install_setup.md
- docs/zh/user_guide.md
- ppsci/solver/solver.py
- ppsci/solver/train.py
- ppsci/utils/symbolic.py
Others 
Docs 
1. 使用文档中的部分功能添加命令行执行方式
2. 修复几处代码问题
> [Doc] Refine user guide

- README.md
- docs/zh/install_setup.md
Others 
Others 
1. 添加基于 develop 分支 commit 粒度的 pip 包
2. 更新安装文档，修复几处不准确的描述
> [PIP] add nightly build pip .whl url

- jointContribution/graphGalerkin/.gitmodules
- jointContribution/graphGalerkin/README.md
Others 
Others 
1. Remove pycamotk for submodules, or error will occur when update --init the submodules in PaddleScience.
> [Git] Remove pycamotk for submodules

- docs/zh/api/experimental.md
- ppsci/experimental/__init__.py
- ppsci/experimental/math_module.py
- test/experimental/test_montecarlo_integrate.py
New fatures
APIs
Add montecarlo integration.
> add montecarlo integrate api

- README.md
- docs/index.md
- docs/zh/examples/aneurysm.md
- docs/zh/examples/bracket.md
- docs/zh/examples/control_arm.md
- docs/zh/install_setup.md
- docs/zh/reproduction.md
- docs/zh/user_guide.md
- examples/RegAE/dataloader.py
- examples/earthformer/sevir_metric.py
- examples/epnn/functions.py
- examples/graphcast/graphcast.py
- examples/heat_exchanger/heat_exchanger.py
- examples/hpinns/functions.py
- examples/phylstm/functions.py
- ppsci/solver/eval.py
- ppsci/solver/printer.py
- ppsci/solver/train.py
Others 
Docs 
1. 更新release/1.3内的所有文档链接，从 `latest/develop` 指向 `release/1.3`
> [Relase/1.3] Change all urls to release/1.3

- docs/zh/examples/amgnet.md
- examples/amgnet/requirements.txt
- examples/phylstm/functions.py
Others 
Others 
1. AMGNet 添加 requirements.txt
2. 删除多余的打印代码
> [Doc] Add requirements.txt for AMGNet

- examples/aneurysm/aneurysm.py
- examples/aneurysm/conf/aneurysm.yaml
- examples/biharmonic2d/conf/biharmonic2d.yaml
- examples/bracket/bracket.py
- examples/bracket/conf/bracket.yaml
- examples/fpde/conf/fractional_poisson_2d.yaml
Bug fixes
Others 
1. 修复EVAL字段不正确的问题
> [Fix] Fix eval config

- ppsci/loss/mtl/base.py
> [Fix] Fix typo in mtl/base

- examples/shock_wave/shock_wave.py
Bug fixes
APIs
1. 修复 ShockWave 输入数据类型和模型参数类型不一致的导致运行报错的问题
> [Fix] Fix input dtype in shock wave

- README.md
- docs/index.md
- ppsci/solver/solver.py
- ppsci/utils/config.py
Others
Docs
1. 支持`iters_per_epoch`设置为-1，根据`constraint`所持有的`dataloader`，自动重新设置`iter_per_epoch`，免去手动设置的过程
2. 首页更新ijcai的代码链接
3. 更新pip安装顺序
> [Feature&Doc] Add ijcai code url

- README.md
- docs/index.md
- docs/zh/examples/spinn.md
- ppsci/data/__init__.py
- ppsci/data/process/batch_transform/__init__.py
- ppsci/solver/eval.py
Others 
Docs 
1. 修复 ijcai 链接指向问题
2. dataloader_cfg支持直接通过传入`collate_fn`的方式指定`collate_fn`
> [Refine&Doc] Fix ijcai url and refien eval code

- ppsci/solver/solver.py
- requirements.txt
Others 
APIs 
1. 分布式环境下暂时取消对Callable Expression的分布式包装，这可能会导致参数同步顺序不正确而报错
2. 更新requirements.txt
> [Fix] Fix dist_wrapper in solver

- examples/tempoGAN/functions.py
Bug fixes
Others
1. fix dereshape_input() of tempoGAN
> [Fix]fix dereshape_input() of tempoGAN

- README.md
- docs/index.md
- docs/zh/examples/nowcastnet.md
Others 
Docs 
1. 添加第七期黑客松比赛相关信息
2. NowcastNet补充数据下载命令
> [Doc] Update 7th hackathon information

- docs/zh/api/arch.md
- docs/zh/examples/brusselator3d.md
- examples/brusselator3d/brusselator3d.py
- examples/brusselator3d/conf/brusselator3d.yaml
- mkdocs.yml
- ppsci/arch/__init__.py
- ppsci/arch/lno.py
Others
Others
1. add lno net
2. add brusselator3d example
> [Example]Add brusselator3d example and LNO net

- docs/zh/examples/brusselator3d.md
- examples/brusselator3d/brusselator3d.py
- examples/brusselator3d/conf/brusselator3d.yaml
- ppsci/arch/lno.py
Bug fixes
Others
1. fix code and doc of brusselator3d
2. fix lno arch
> [Fix]Fix code and doc of example brusselator3d; Fix lno arch;

- README.md
- docs/index.md
- docs/zh/examples/brusselator3d.md
- examples/brusselator3d/brusselator3d.py
Others
Others
1. fix lines of code of doc
2. fix code
3. add ai-studio url
> [Fix]fix and update brusselator3d

- docs/zh/examples/heat_pinn.md
<!-- One of Bug fixes
One of Docs 
Modify the document of heat_pinn
> Modify the document of heat_pinn

- README.md
Others 
Others 
pip方式下载末尾添加清华源，提升依赖下载速度
> [PIP] Update tsinghua index for pip install

- docs/zh/api/geometry.md
- docs/zh/install_setup.md
- mkdocs.yml
- ppsci/geometry/__init__.py
- ppsci/geometry/mesh.py
- ppsci/geometry/sdf.py
New features
APIs 
1. 添加基于sdf的隐式几何类`SDFMesh`，避免因为环境导致`pymesh`无法安装而无法运行基于复杂几何的案例
> [Fea] Support for SDFMesh based on warp-lang

- examples/transformer4sr/conf/transformer4sr.yaml
- examples/transformer4sr/transformer4sr.py
- ppsci/arch/transformer.py
Bug fixes
Others
1. switch paddle.load to ppsci.utils.save_load.load_pretrain
2. fix transformer arch
3. update eval data to get doc's result
> [Example]fix bug of transformer4sr

- examples/heart/conf/forward.yaml
- examples/heart/equation.py
- examples/heart/forward.py
Others
Others
The code provides a deformation prediction for the left ventricle during the diastolic phase under a linear elastic constitutive model, utilizing 20% of the actual data points for validation to achieve improved accuracy.
> [Example] Add an example of predicting forward diastolic deformation of the left ventricular myocardium

- ppsci/optimizer/optimizer.py
New features
APIs 
基于<https://github.com/PaddlePaddle/Paddle/pull/68079>，为 Adam/AdamW 支持amsgrad参数
> [Fea] Support amsgrad in Adam/AdamW

- ppsci/solver/solver.py
- ppsci/utils/save_load.py
- test/loss/aggregator.py
Bug fixes
APIs 
修复Solver中`loss_aggregator`初始化在load_checkpoint之后，导致载入时找不到`loss_aggregator`而报错的问题，因此将`loss_aggregator`相关代码适当向上移动
> [Fix] Fix aggregator error when load ckpt

- README.md
- docs/index.md
- docs/zh/development.md
- docs/zh/examples/nlsmb.md
- docs/zh/examples/tempoGAN.md
- docs/zh/install_setup.md
- docs/zh/user_guide.md
Others 
Docs 
1. pip改为python -m pip ，避免用户pip和python不对应时安装后无法正常使用ppsci问题
2. 更新PIR下的推理模型说明，优化几处文档错误
> [Doc] Refine pip install script

- docs/zh/examples/brusselator3d.md
- examples/brusselator3d/brusselator3d.py
- ppsci/arch/lno.py
Others
Others
1. support export and infer
2. update doc
> [Example]support export&infer of brusselator3d example and update doc

- docs/zh/examples/deepcfd.md
Others
Docs
add url of AI Studio in doc of DeepCFD
> [Doc]update doc of DeepCFD
