PaddlePaddle/PaddleScience

paddlescience/loss/loss_base.py
This PR cleans api_new parameter, which is useless now. This parameter was used for compatibility of jacobian/hessian version.
=> clean api_new parameter

paddlescience/geometry/geometry.py, requirements.txt
New features
Others
Add .stl file.
功能描述：
增加对stl文件的识别，可以解析不规则的几何体。引入了两个库，分别是pyvista和pysdf。
使用的example如下：
```
import paddlescience as psci
import numpy as np
import paddle
paddle.seed(1)
np.random.seed(1)
geo = psci.geometry.Rectangular(origin=(0, 0, 0), extent=(2000, 200, 2500))
geo.add_boundary(name="inlet", criteria=lambda x, y, z: abs(x) < 1e-5)
geo.add_boundary(name="outlet", criteria=lambda x, y, z: abs(x - 2000) < 1e-5)
geo.add_boundary(name='wing', filename='NACA.STL')
geo_disc = geo.discretize(method="uniform", npoints=[201, 21, 26])
pde = psci.pde.NavierStokes(
nu=0.01, rho=1.0, dim=3, time_dependent=False, weight=0.0001)
bc_inlet_u = psci.bc.Dirichlet('u', rhs=1.0)
bc_inlet_v = psci.bc.Dirichlet('v', rhs=0.0)
bc_inlet_w = psci.bc.Dirichlet('w', rhs=0.0)
bc_outlet_p = …
```
=> add .stl file

paddlescience/config.py, paddlescience/solver/solver.py
Bug fixes
APIs
https://github.com/PaddlePaddle/PaddleScience/pull/120 为`psci.solver.Solver`接口添加CINN支持，但由于`config.prim_enabled()`开启时就会走`config.prim2orig()`逻辑转换为原生算子，导致模型根本没能走到CINN。本PR修复了该问题。
=> fix PR120 CINN support bug

paddlescience/geometry/__init__.py, paddlescience/geometry/geometry.py, paddlescience/geometry/polydata.py, paddlescience/geometry/rectangular.py, paddlescience/visu/visu_vtk.py
New features
Others
Supports geometries such as triangles via pyvista polydata.
功能描述：
1、引入pyvista定义的polydata，通过vertices和faces可以灵活地支持多种几何构造，下面示例展示了三角形的构造
2、在rectangle上增加准随机采样，包括lhs、sobol、halton等
3、初步支持减法的布尔运算
使用示例如下：
```
import paddlescience as psci
import numpy as np
import paddle
paddle.seed(1)
np.random.seed(1)
vertices = np.array([[3, 3, 0], [7, 3, 0], 
[5, 7, 0], [3, 3, 0.5], 
[7, 3, 0.5], [5, 7, 0.5]])
faces = np.hstack(
[
[3, 0, 2, 1],  # triangle
[3, 3, 4, 5],  # triangle
[4, 0, 3, 5, 2], # square
[4, 1, 2, 5, 4], # square
[4, 0, 1, 4, 3],  # square
]
)
triangle = psci.geometry.PolyData(vertices, faces)
geo = psci.geometry.Rectangular(origin=(0, 0, 0), extent=(10, 10, 0.5))
geo = geo - triangle
geo.add_boundary(name="inlet", criteria=lambda x, y, z: abs(x) < 1e-5) …
```
=> Supports geometries such as triangles via pyvista polydata.

paddlescience/geometry/geometry.py, paddlescience/geometry/geometry_discrete.py, paddlescience/geometry/rectangular.py
New features
Others
Boundary refinement.
功能描述：增加了局部加密的API接口，使用示例如下：
```
import paddlescience as psci
import numpy as np
import paddle
vertices = np.array([[3, 3, 0], [7, 3, 0], 
[5, 7, 0], [3, 3, 0.5], 
[7, 3, 0.5], [5, 7, 0.5]])
faces = np.hstack(
[
[3, 0, 2, 1],  # triangle
[3, 3, 4, 5],  # triangle
[4, 0, 3, 5, 2], # square
[4, 1, 2, 5, 4], # square
[4, 0, 1, 4, 3],  # square
]
)
triangle = psci.geometry.PolyData(vertices, faces)
geo = psci.geometry.Rectangular(origin=(0, 0, 0), extent=(10, 10, 0.5))
geo = geo - triangle
geo.add_boundary(name="inlet", criteria=lambda x, y, z: abs(x) < 1e-5)
geo.add_boundary(name="outlet", criteria=lambda x, y, z: abs(x - 10) < 1e-5)
geo.add_boundary(name="triangle", filename=triangle)
geo_disc = geo.discretize(method="quasi_sobol", npoints= 3000) …
```
=> Boundary refinement.

paddlescience/solver/solver.py
Bug fixes
APIs 
修复了多卡自动并行机制下，开始计时位置不正确的问题
=> move timing position ahead of training

requirements.txt
Bug fixes
Requirements
Fix `pyvista==0.37.0`, for 0.38.0 is not stable and will cause error during installion.
=> Fix requirement for pyvista

paddlescience/solver/utils.py
Others
Others
`with_data_parallel`预计于paddle2.5版本移除。此处是为了开启`build_cinn_pass`，paddle develop分支现在已经支持不使用`with_data_parallel`就打开`build_cinn_pass`，因此直接移除了这里对`with_data_parallel`的使用。
The api `with_data_parallel` will be deprecated in paddle2.5. The purpose of `with_data_parallel` here is to `build_cinn_pass`. howerver, such operation doesn't need to use `with_data_parallel` with current `paddle`(develop). So just delete it.
=> remove with_data_parallel

examples/ldc/ldc2d_steady_Re10.py, examples/ldc/ldc2d_unsteady_Re10.py, ppsci/__init__.py, ppsci/constraint/boundary_constraint.py, ppsci/constraint/initial_constraint.py, ppsci/constraint/integral_constraint.py, ppsci/constraint/interior_constraint.py, ppsci/data/__init__.py, ppsci/data/dataset/__init__.py, ppsci/data/dataset/array_dataset.py, ppsci/equation/pde/navier_stokes.py, ppsci/geometry/geometry.py, ppsci/geometry/mesh.py, ppsci/geometry/pointcloud.py, ppsci/geometry/timedomain.py, ppsci/solver/__init__.py, ppsci/solver/eval.py, ppsci/solver/printer.py, ppsci/solver/solver.py, ppsci/solver/train.py, ppsci/solver/visu.py, ppsci/utils/misc.py, ppsci/visualize/__init__.py, ppsci/visualize/base.py, ppsci/visualize/plot.py, ppsci/visualize/visualizer.py, ppsci/visualize/vtu.py
New features
APIs 
主要修改点：
1. 添加ldc2d_unsteady(Re=10)
其他：
1. 修复 `TimeDomain` 在给定 `criteria` 时，将 criteria 筛选步骤放置在空间-时间采样之后的BUG，预期逻辑应该是先进行空间采样，然后用criteria对空间采样点进行过滤，然后再进行时间采样，最后生成空间-时间数据，而目前的逻辑是空间采样->时间采样->criteria，这会导致实际生成的数据中，每个时间戳对应的一段数据的t并不都一致（如时刻t0对应的数据data_t0=[N, 3]， 其中data_t0[:, 0]的元素并不都等于t0)
2. 添加 `Visualizer` 基类，以及根据保存数据的结构不同，派生的几个类，以此从 eval 中将可视化过程分离为单独的`Solver.visualize` 方法
3. 按照import依赖先后关系，调整 `ppsci/__init__.py` 中import的顺序，避免找不到包的问题
=> Add ldc2d unsteady re10 case

docs/zh/examples/cylinder2d_unsteady.md, ppsci/arch/__init__.py, ppsci/data/dataloader.py
Bug fixes
Docs
1. 修复cylinder 2d文档中引用的路径问题；
2. 修复InfiniteDataLoader传入IterableDataset类型时的报错
=> fix cylinder2d doc and InfiniteDataLoader

test_tipc/README.MD, test_tipc/benchmark_train.sh, test_tipc/configs/train_2d_unsteady_continuous/prepare_2d_unsteady_continuous.txt, test_tipc/configs/train_2d_unsteady_continuous/train_2d_unsteady_continuous.txt, test_tipc/prepare.sh
Bug fixes
1. fix README.MD to the standard process of running the script
2. export environment variables in train.sh because strict bash format
ensure the way of running benchmarks like:
```
export script_path=xxx
bash ./test_tipc/prepare.sh $script_path benchmark_train
bash ./test_tipc/benchmark_train.sh  $script_path benchmark_train
```
=> fit current running steps into standard

docs/zh/examples/cylinder2d_unsteady.md, docs/zh/examples/ldc2d_unsteady.md, ppsci/loss/l1.py, ppsci/loss/l2.py, ppsci/loss/mse.py, ppsci/metric/l2_rel.py, ppsci/metric/mae.py, ppsci/metric/mse.py, ppsci/metric/rmse.py
…lization
Others
Docs
主要修改点
1. 替换文档数学公式中的 `\frac` 为 `\dfrac` 以保持分子和分母的大小与普通字符一致
2. 根据 https://latex.org/forum/viewtopic.php?t=21301 ，替换文档数学公式中的 `\sum` 为 `\sum\limits` 以强制上下界表达式在 $\Sigma$ 符号的正上方和正下方
=> change \frac to \dfrac

docs/zh/api/arch.md, ppsci/arch/__init__.py, ppsci/arch/model_list.py
New features
APIs
主要修改点：
针对多模型场景，添加 `Class ModelList` 用以将多个在训练时共享输入（或共享一部分输入）的模型包装为一个集成的模型
=> add ModelList for multiple models case

.gitignore, mkdocs.yml, ppsci/arch/model_list.py, ppsci/data/__init__.py, ppsci/data/process/batch_transform/__init__.py, ppsci/data/process/transform/__init__.py, ppsci/solver/eval.py
改进 `default_collate_fn` 以支持加载含 `None` 的数据
APIs
主要修改点：
1. 参考 Paddle 已有的 `default_collate_fn`，修改得到 `_default_collate_fn_allow_none`，以支持某一字段为None的情况，该函数允许样本中含有 `None` 字段，此时组完 batch 后返回的也是 `None`。
2. 优化 `collate_fn_batch_transforms` 代码，复用 `_default_collate_fn_allow_none` 函数，减少冗余代码
其他：
1. 令 `transform` 和 `batch_transform` 模块在 `ppsci.data` 下可见，同时修改了其在 API 文档中的路径
2. 在 `ModelList` 中对传入的模型列表包裹一层 `nn.LayerList` 以让模型列表的属性能被正常注册到 Layer 中
3. 修正了 `eval_func` 返回值的type hint
=> Improve default_collate_fn to allow None field in data.

ppsci/data/__init__.py, ppsci/data/process/batch_transform/__init__.py
move `_default_collate_fn_allow_none` to `ppsci.data.batch_transform` to avoid unfound error
Bug fixes
APIs
主要修改点：
1. 移动 `_default_collate_fn_allow_none` 函数至 `ppsci/data/process/batch_transform/__init__.py` 文件中，防止 import 相互依赖导致 `_default_collate_fn_allow_none` 找不到
=> move _default_collate_fn_allow_none to ppsci.data.batch_transform

ppsci/data/dataset/trphysx_dataset.py, ppsci/optimizer/lr_scheduler.py
Others
APIs
主要修改点：
1. 按照python3的风格，移除调用父类初始化方法时 `super()` 括号内的显式参数
=> remove args in super(...).__init__(...) for python3 style

ppsci/solver/visu.py
Bug fixes
APIs 
主要修改点：
1. 个别案例如 VIV 需要可视化具有物理意义的高阶微分变量，故使用 `eval_with_no_grad` 控制可视化函数上的中是否开启梯度功能
=> control no_grad for visualize_func

ppsci/utils/expression.py
Bug fixes
APIs
主要修改点：
1. 在 `output_dict` 中添加来自 `input_dict` 的 `area` 字段供损失函数计算加权使用
=> add 'area' from input_dict into output_dict

ppsci/solver/solver.py, ppsci/solver/visu.py, ppsci/utils/expression.py, ppsci/utils/misc.py
New features
APIs
主要修改点：
1. 支持多卡 python 推理，完善几处 typehint 和 docstring
多卡 python 推理主要步骤：
- step1 pad，将输入数据的数量，补齐到能被卡数整除
- step2 shard，均匀切分数据到每张卡上（step1 保证了数据能被均匀切分，不均匀切分可能会在 all_gather 时 hang 住）
- step3 local batch predict，每张卡根据切分得到的数据，并根据设置的 batch size，逐 batch 前向预测
- step4 local batch concat，每张卡上各自拼接batch wise的预测结果
- step5 all gather(and concat)，每张卡拿到所有卡上的预测结果并再次拼接
- step6 rearange，根据数据切分产生的数据下标置换 $p$，求出其逆置换 $inv(p)$，将数据按逆置换排列，恢复顺序，与 input_dict 内的数据一一对应
- step7 discard pad，重新排列完毕之后，丢弃末尾的对应pad数据的冗余预测结果
- step8 return result，返回推理结果
正确性验证代码（num_samples=3+n_gpu=1,..,7+batch_size=31，num_samples=1153+n_gpu=1,...,7 +batch_size=31 的环境下均验证通过）：
``` python
import ppsci
import paddle
def run():
paddle.seed(42)
bs = 31
input_dict = paddle.load("./input_dict.pddata")
for v in input_dict.values(): …
```
=> support multi-gpu prediction

ppsci/data/__init__.py
Others
Others
add judgment of dataloader's length to avoid getting empty batch
=> add judgment of dataloader's length

docs/zh/install_setup.md, ppsci/metric/anomaly_coef.py, ppsci/metric/l2_rel.py, ppsci/metric/mae.py, ppsci/metric/mse.py, ppsci/metric/rmse.py, ppsci/utils/expression.py, ppsci/visualize/plot.py
Others 
Docs 
主要修改点：
参照 #356 
1. 文档 "文档与使用" 章节中添加 pip 安装描述
2. 修复个别 docstrings 存在的冗余括号问题
=> Update develop doc

ppsci/arch/mlp.py, ppsci/autodiff/ad.py, ppsci/equation/pde/biharmonic.py, ppsci/equation/pde/laplace.py, ppsci/equation/pde/linear_elasticity.py, ppsci/equation/pde/navier_stokes.py, ppsci/equation/pde/normal_dot_vec.py, ppsci/equation/pde/poisson.py, ppsci/equation/pde/viv.py, ppsci/geometry/mesh.py, ppsci/loss/integral.py
Others 
Docs 
主要修改点：
1. 为 `Equation` 模块下的部分公式的 docstring 添加对应 mathjax 公式
2. 修复 `IntergralLoss` 公式描述错误的问题
其他：
1. 修复 `Mesh.scale` 未赋值回原变量导致该接口实际无效的问题
3. 优化几处接口的 docstring 和代码结构
=> add mathjax expression for equations and fix some code

ppsci/equation/pde/linear_elasticity.py, ppsci/geometry/mesh.py
Others 
APIs 
1. 修复 `LinearElasticity` 公式粗体问题
2. 完善 mesh 缺少包的报错信息
=> Fix formula and refine err hint

ppsci/autodiff/ad.py
Others 
APIs 
主要修改点：
1. 规范 ad.py 的代码，添加对应公式，完善注释和报错信息
=> update formula and code for autodiff

test/equation/test_laplace.py
Others 
APIs 
主要修改点：为 ppsci.equation.pde.Laplace 类添加单元测试
``` sh
pytest --cov=./ppsci/equation/pde test/equation/test_laplace.py
```
``` sh
platform linux -- Python 3.7.16, pytest-7.3.1, pluggy-1.0.0
rootdir: /workspace/hesensen/PaddleScience
plugins: anyio-3.6.2, dash-2.9.2, cov-4.1.0
collected 2 items                                                                                                                                                              
test/equation/test_laplace.py ..                                                                                                                                         [100%]
---------- coverage: platform linux, python 3.7.16-final-0 -----------
Name                                      Stmts   Miss  Cover …
```
=> add unit test for Laplace

ppsci/geometry/geometry_3d.py
Others 
Others 
https://github.com/PaddlePaddle/PaddleScience/issues/376 case7
=> [add sdf] sphere

test/equation/test_normal_dot_vec.py
Others
Others
add unit test for `normal_dot_vec.py`
```
pytest --cov=./ppsci/equation/pde test/equation/test_normal_dot_vec.py
========================================================= test session starts ==========================================================
platform linux -- Python 3.10.6, pytest-7.3.2, pluggy-1.0.0
rootdir: /home/greatx/repos/PaddleScience
plugins: anyio-3.7.0, cov-4.1.0
collected 1 item                                                                                                                       
test/equation/test_normal_dot_vec.py .                                                                                           [100%]
---------- coverage: platform linux, python 3.10.6-final-0 -----------
Name                                      Stmts   Miss …
```
=> add unit test for normal_dot_vec

ppsci/geometry/geometry_2d.py, pyproject.toml
New features
APIs
#376 
In this pull request, I have added the sdf_func implementations for disk The visual result can be tested using the following code:
~~~python
import os
print(os.environ['PYTHONPATH'])
import ppsci
from ppsci import visualize
geo = ppsci.geometry.Disk((0.0, 0.0), 1.0)
points_dict = geo.sample_interior(n=10000) # 可视化10000个点
visualize.vtu.save_vtu_from_dict("./visualize_sdf.vtu", points_dict, geo.dim_keys, ("sdf", ))
~~~
Visualize results with ParaView software:
Also, add ignore:"E741" for tool.ruff
=> [Feature] Add disk sdf_func

ppsci/geometry/geometry_2d.py
New features
APIs
In this pull request, I have added the sdf_func implementations for rectangles and triangles. The visual result can be tested using the following code:
```python
import ppsci
import numpy as np
from matplotlib import pyplot as plt
geo = ppsci.geometry.Triangle((0, 0), (1, 0), (0, 1))
x = np.linspace(-0.5, 1.3, 1000)
y = np.linspace(-0.5, 1.3, 1000)
X, Y = np.meshgrid(x, y)
x = X.flatten()
y = Y.flatten()
Z = geo.sdf_func(np.stack([x, y], axis=-1)).reshape(X.shape)
plt.contour(X, Y, Z, 0, colors="black")
plt.contourf(X, Y, Z, 20, cmap="RdBu_r")
plt.colorbar()
plt.show()
```
**Visual Result** 
https://github.com/PaddlePaddle/PaddleScience/issues/376
=> [Feature] Add rectangle and triangle sdf_func

test/equation/test_poisson.py
Others
Others
https://github.com/PaddlePaddle/PaddleScience/issues/378 3.6 poisson
add unit test for poisson
```bash
aistudio@jupyter-115720-6409174:~/PaddleScience$ pytest --cov=./ppsci/equation/pde test/equation/test_poisson.py
========================================================================= test session starts ==========================================================================
platform linux -- Python 3.8.8, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/aistudio/PaddleScience
plugins: anyio-3.7.0, cov-4.1.0
collected 2 items                                                                                                                                                      
test/equation/test_poisson.py .. …
```
=> add test for poisson

test/equation/test_pde_base.py
Others
Others
Adding unittest for equation/pde/base.py
```
---------- coverage: platform win32, python 3.9.13-final-0 -----------
Name                                                                                          Stmts   Miss  Cover
-----------------------------------------------------------------------------------------------------------------
C:\Users\kinet\anaconda3\envs\paddle\Lib\site-packages\ppsci\equation\pde\__init__.py             8      0   100%
C:\Users\kinet\anaconda3\envs\paddle\Lib\site-packages\ppsci\equation\pde\base.py                26      0   100%
C:\Users\kinet\anaconda3\envs\paddle\Lib\site-packages\ppsci\equation\pde\biharmonic.py          17     13    24%
C:\Users\kinet\anaconda3\envs\paddle\Lib\site-packages\ppsci\equation\pde\laplace.py             15 …
```
=> Adding unittest for equation/pde/base.py

test/equation/test_viv.py
Others
Others
3.7 add unittest for viv
- #378
=> add unittest for viv

ppsci/geometry/geometry_1d.py
New features
APIs
It implements the SDF function for `Geometry/Interval` class, for an interval `[l, r]`, the sdf function is defined as:
$$
sdf(x) = -\min(x-l, r-x) = (\frac{r-l}{2} - |x-(l+r)|/2))/2
$$
=> adding sdf_func to interval

test/equation/test_biharmonic.py
Others 
Others 
add unit test for `biharmonic`
=> add unit test for biharmonic

ppsci/geometry/geometry_2d.py
New features
APIs
#376
测试代码
```python
import ppsci
from ppsci.utils import logger
from ppsci import visualize
logger.init_logger()
geo = ppsci.geometry.Polygon(((0, 0), (1, 0), (2, 1), (2, 2), (0, 2)))
points_dict = geo.sample_interior(n=100000) # 可视化100000个点
visualize.vtu.save_vtu_from_dict("./visualize_sdf.vtu", points_dict, geo.dim_keys, ("sdf", ))
```
=> add Polygon sdf

docs/zh/user_guide.md
Others 
Docs 
主要修改点：
1. 完善 [使用指南] 文档并修正部分描述错误
=> refine user_guide

test/equation/test_linear_elasticity.py
Others
Others
为equatiohn/pde/linear_elasticity.py添加单元测试
=> 为equatiohn/pde/linear_elasticity.py添加单元测试

test/equation/test_navier_stokes.py
=> 为 PaddleScience 的 equation 模块添加单元测试 test_navier_stokes

ppsci/geometry/csg.py, ppsci/geometry/geometry_1d.py
New features
APIs
主要修改点：
1. 为简单几何的 CSG 布尔操作添加 sdf_func 的运算
2. 修复 `Interval` 几何 sdf_func 计算错误的问题
=> Add sdf for bool operation for simple geometries

ppsci/utils/logger.py
APIs 
主要修改点：
1. 为了避免用户在调试过程中，使用`logger`模块打印信息，或者内部的一些日志调用`logger`之前，还需手动调用`logger.init_logger`这一函数否则会报错的问题，减少不必要的代码量，提升用户体验。因此在调用`logger`模块下的日志打印函数之前，若未手动调用`init_logger`对全局单例`_logger`进行初始化，则自动调用`init_logger`进行初始化，但由于自动初始化的`log_file`为未指定的None，因此只会打印信息到终端，而不会同步输出到文件中。
=> Automatically initialize logger when it is not initialized

examples/operator_learning/deeponet.py
Bug fixes
Others 
主要修改点：
1. 修复 DeepONet 代码末尾没有将模型预测结果从Tensor转成numpy，导致matplotlib报错的问题
=> convert Tensor to numpy for result of Solver.predict in DeepONet code

ppsci/constraint/base.py, ppsci/solver/train.py
Bug fixes
APIs
Constraint中取消使用 InfiniteDataLoader 包装 dataloader，因为这会导致多卡训练时程序卡住的问题。
添加 StopIteration 捕捉迭代器是否迭代结束。
=> fix program stuck when use distributed training

ppsci/solver/train.py
Bug fixes
APIs 
主要修改点：
1. 修复 `train.py` 中 `expr_dicts` 生成时未从generator转成tuple，导致 to_static 跟踪的函数签名发生变化而一直处于动转静过程
=> [Fix] Fix to static failure for wrong type of expr_dicts

ppsci/data/dataset/array_dataset.py
Bug fixes
APIs 
主要修改点：
1. 允许 `IterableNamedArrayDataset` 初始化时参数 weight 为 None
=> [Fix] Fix IterableNamedArrayDataset when weight is None

.readthedocs.yaml
Bug fixes
Docs 
1. 按照 ReadTheDocs 官网要求 https://blog.readthedocs.com/migrate-configuration-v2/ ，添加 `.readthedocs.yaml` 配置文件
=> [Doc] Add readthedocs.yaml file required by ReadTheDocs

examples/ldc/ldc2d_unsteady_Re10.py, ppsci/constraint/initial_constraint.py, ppsci/constraint/interior_constraint.py, ppsci/geometry/geometry.py, ppsci/geometry/mesh.py, ppsci/geometry/timedomain.py
New features
APIs 
1. 为 Geometry 模块添加对 SDF 函数计算其在各个方向的微分的功能
2. 完善 `TimeXGeometry` 的 SDF 功能
=> [WIP][Feature] Add derivatives for SDF

ppsci/probability/hmc.py, test/probability/test_hmc.py, test/probability/test_hmc2.py
- 将API的目标参数按照Pyro的API调整为集合形式，以便对多个参数同时进行采样。
- run_chain中增加warmup阶段。
- 新增测试案例。
如果需要达到和Pyro等一样的速度需要在采样时加入调整步长的功能。
=> update HMC API

docs/zh/examples/shock_wave.md, ppsci/geometry/geometry_nd.py
Others 
Docs 
1. 修正 shockwave 文档公式，去掉 $\rho$
2. 去除 `geometry_nd.py` 中的警告
=> [Fix] Refine shock wave document; remove redundant warning of geometry_nd.py

ppsci/solver/solver.py
Bug fixes
APIs 
1. 删除多余的 self.eval 语句
=> [Fix] remove redundant eval call in solver.train

docs/zh/examples/tempoGAN.md, examples/tempoGAN/functions.py, ppsci/data/dataset/array_dataset.py, ppsci/data/dataset/csv_dataset.py, ppsci/data/dataset/mat_dataset.py, ppsci/data/dataset/npz_dataset.py, ppsci/data/process/transform/preprocess.py
Others
APIs
1. apply transforms also on label and weight
2. update tempoGAN example
=> Apply transforms on label and weight

ppsci/solver/eval.py
Bug fixes
APIs
修复 eval.py _eval_by_dataset 中未将指标转为float导致返回的指标为inf的BUG
=> [Fix] fix type in _eval_by_dataset

README.md, docs/index.md, docs/zh/examples/bracket.md, docs/zh/user_guide.md, examples/bracket/bracket.py, examples/bracket/conf/bracket.yaml, mkdocs.yml, ppsci/solver/solver.py, requirements.txt
New features
Others 
1. 添加第三方库 [hydra](https://hydra.cc/docs/0.11/intro/) 控制运行配置，并适配 bracket 案例
2. bracket 案例代码重构，添加评估函数 `evaluate`，及其训练/评估命令和预训练模型、指标
3. 使用指南添加 hydra 相关教程
4. 删除 `Solver.from_config`
=> [Feature] Add hydra configuration module and adapt bracket to hydra

docs/zh/examples/bracket.md, examples/bracket/bracket.py
Bug fixes
Others 
1. 修复 eval_during_train 调用时访问的字段不正确问题
2. 修复 bracket.md 中的描述错误
=> [Fix] Correct eval_during_train position

docs/zh/examples/bracket.md, examples/bracket/conf/bracket.yaml
Bug fixes
Others 
1. 通过黑名单的方式修复 hydra 配置文件运行时通过命令行指定的参数含有`/`可能导致创建多级目录的BUG
=> [Fix] fix hydra using hydra.job.config.override_dirname.exclude_keys

docs/zh/examples/laplace2d.md, examples/laplace/conf/laplace2d.yaml, examples/laplace/laplace2d.py
Others
Others 
laplace2d 案例代码重构
=> modify laplace2d to hydra style

docs/zh/examples/phylstm.md, examples/phylstm/conf/phylstm2.yaml, examples/phylstm/conf/phylstm3.yaml, examples/phylstm/phylstm2.py, examples/phylstm/phylstm3.py
=> hydra 改造 phylstm

docs/zh/development.md, ppsci/utils/symbolic.py
Bug fixes
APIs
1. 修复符号化计算时微分阶数为 `SympyNumber` 而非 Python built-in int 的问题
2. 修复开发文档里的 `NewValidator` 的调用方式错误
=> [Fix] Convert order from SympyNumber to python built-in number in symbolic

docs/zh/examples/bubble.md, examples/bubble/bubble.py, examples/bubble/conf/bubble.yaml
=> 【hydra No.20】改造 bubble

docs/zh/examples/hpinns.md, examples/hpinns/conf/hpinns.yaml, examples/hpinns/holography.py
=> 【hydra No.11】for hpinns model

examples/bubble/bubble.py, ppsci/autodiff/ad.py
APIs 
1. 为 `ppsci.autodiff.jacobian/hessian` 添加 `retain_graph/create_graph` 两个选项，可将 `create_graph` 设置为 `False` 以显著减少推理含有微分操作场景下的显存占用（推理时不需要进行梯度反传，因此 grad 操作不需要创建反向图，从而减少不必要的变量创建）。
=> [Enhance] add retain_graph/create_graph options for jacobian and hessian

docs/zh/examples/deeponet.md, examples/operator_learning/conf/deeponet.yaml, examples/operator_learning/deeponet.py
Others 
Others 
15 deeponet
因数据集需要注册yale.edu后缀邮箱下载，无法获取数据集，只是修改代码没有运行测试
=> 【hydra No.15】deeponet

docs/zh/examples/deepcfd.md, examples/deepcfd/conf/deepcfd.yaml, examples/deepcfd/deepcfd.py
Others
Others
DeepCFD 案例代码重构，添加评估函数 evaluate，及其训练命令。
=> 【hydra No.18】Adapt DeepCFD to hydra

ppsci/data/__init__.py
Bug fixes
APIs
When setting a data-loader config without a sampler:
```
train_dataloader_cfg = {
"dataset": {
"name": "NamedArrayDataset",
"input":input_train,
"label":label_train
},
"batch_size": Nb_train,
'iters_per_epoch':ITERS_PER_EPOCH,
}
```
Logics in `def build_dataloader(_dataset, cfg):` will triger `sampler=None`. This leads to no processing being performed on the input data（No batch is composed， naked __getitem(0)).
Then a raise or warning is necessary. NS
=> Bugfix nosampler

docs/zh/examples/tempoGAN.md, examples/tempoGAN/conf/tempogan.yaml, examples/tempoGAN/tempoGAN.py
=> 【hydra No.17】tempoGAN

docs/zh/examples/deephpms.md, examples/deephpms/burgers.py, examples/deephpms/conf/burgers.yaml, examples/deephpms/conf/korteweg_de_vries.yaml, examples/deephpms/conf/kuramoto_sivashinsky.yaml, examples/deephpms/conf/navier_stokes.yaml, examples/deephpms/conf/schrodinger.yaml, examples/deephpms/korteweg_de_vries.py, examples/deephpms/kuramoto_sivashinsky.py, examples/deephpms/navier_stokes.py, examples/deephpms/schrodinger.py
=> 【hydra No.12】deephpms

jointContribution/XPINNs/XPINN_2D_PoissonsEqn.py, ppsci/optimizer/lr_scheduler.py
Others 
Others 
1. 基于 PaddlePaddle/Paddle#57507，在 XPINNs 案例中使用支持 float64 的 `Assign` API 代替原有复杂写法
2. 修复 `lr_scheduler` 模块中不正确的 Example 代码
=> [Fix] use Assign with fp64 in XPINNs

docs/zh/examples/aneurysm.md, examples/aneurysm/aneurysm.py, examples/aneurysm/conf/aneurysm.yaml
Others
Others
* https://github.com/PaddlePaddle/PaddleScience/issues/571 
No.4 aneurysm
1、使用第三方库 [hydra](https://hydra.cc/docs/0.11/intro/)适配 aneurysm案例
2、aneurysm案例代码重构，添加评估函数 evaluate，及其训练/评估命令和预训练模型、指标
=> 【hydra No.4】aneurysm

docs/zh/examples/cylinder2d_unsteady_transformer_physx.md, docs/zh/examples/lorenz.md, docs/zh/examples/rossler.md, examples/cylinder/2d_unsteady/transformer_physx/conf/enn.yaml, examples/cylinder/2d_unsteady/transformer_physx/conf/transformer.yaml, examples/cylinder/2d_unsteady/transformer_physx/train_enn.py, examples/cylinder/2d_unsteady/transformer_physx/train_transformer.py, examples/lorenz/conf/enn.yaml, examples/lorenz/conf/transformer.yaml, examples/lorenz/train_enn.py, examples/lorenz/train_transformer.py, examples/rossler/conf/enn.yaml, examples/rossler/conf/transformer.yaml, examples/rossler/train_enn.py, examples/rossler/train_transformer.py
Others 
Others 
13 lorenz 
14 rossler
16 cylinder2d_unsteady_transformer_physx
=> 【hydra No.13、14、16】lorenz/rossler/cylinder2d_unsteady_transformer_physx

docs/zh/examples/viv.md, examples/fsi/conf/viv.yaml, examples/fsi/viv.py
Others
Others
Adapt VIV to hydra
- #571
=> 【hydra No.3】Adapt VIV to hydra

docs/zh/examples/cylinder2d_unsteady.md, examples/cylinder/2d_unsteady/conf/cylinder2d_unsteady.yaml, examples/cylinder/2d_unsteady/cylinder2d_unsteady_Re100.py
Others
Others
No.9 cylinder2d_unsteady
1、使用第三方库 [hydra](https://hydra.cc/docs/0.11/intro/)适配 cylinder2d_unsteady案例
2、cylinder2d_unsteady案例代码重构，添加评估函数 evaluate，及其训练/评估命令和预训练模型、指标
=> 【hydra No.6】cylinder2d_unsteady

docs/zh/examples/cylinder2d_unsteady.md, docs/zh/examples/darcy2d.md, docs/zh/examples/ldc2d_steady.md, docs/zh/examples/ldc2d_unsteady.md, docs/zh/user_guide.md
Others 
Docs 
1. 添加 cylinder2d_unsteady_Re100、darcy2d 的预训练模型、评估命令和评估指标
2. 修正预训练模型的名字，`xxx_pretrain.pdparams` --> `xxx_pretrained.pdparams`
=> [Doc] Add pretrained model for cylinder2d_unsteady_Re100, darcy2d and fix filename

docs/zh/examples/phylstm.md, jointContribution/PIRBN/jacobian_function.py, ppsci/solver/solver.py, ppsci/utils/misc.py
Others 
APIs 
1. 由于 `CUDAPinnedPlace` 暂时不支持部分分布式通讯API，因此 `misc.all_gather` 时遇到从 dataloader 中直接拿到 `CUDAPinnedPlace` 设备类型的数据时，手动转换到 `CUDAPlace`，避免报错。
2. 修复 PIRBN grad 报错问题
=> [Fix] Fix for all_gather is not supported by CUDAPinnedPlace and PIRBN

docs/zh/examples/heat_pinn.md, docs/zh/examples/phylstm.md, examples/heat_pinn/heat_pinn.py, ppsci/solver/solver.py
Bug fixes
Others 
1. 在 `Solver.predict` 返回前，删除在 `input_dict` 末尾 padding 的数据，避免影响输入数据
2. 规范 heat_pinn 案例的精度指标格式，修正代码拼写错误：`mes`-->`mse`
=> [Fix] Remove padding data at the end of solver.predict

docs/zh/examples/control_arm.md, examples/control_arm/inverse_parameter.py, ppsci/arch/base.py
Others
Others
1. Fix arch.freeze/unfreeze
2. Change eval of control_arm example from MAE to L2Rel
=> [Fix]Fix arch.freeze/unfreeze and change eval of control_arm example

docs/zh/examples/amgnet.md, examples/amgnet/amgnet_airfoil.py, examples/amgnet/amgnet_cylinder.py, examples/amgnet/conf/amgnet_airfoil.yaml, examples/amgnet/conf/amgnet_cylinder.yaml
Others 
Docs 
1. 修复 AMGNet 文档命令拼写错误
2. 修复 AMGNet 代码未固定种子和初始化logger的问题，配置文件添加 `exclude_keys`
=> [Fix] add exclude_keys for amgnet yaml and fix document typo

ppsci/solver/printer.py
Others
Others
修改gpu_mem 单位B->MB
=> 【benchmark】fix gpu_mem unit

ppsci/__init__.py, pyproject.toml, setup.py
Others 
Others 
1. 添加 scm 工具，pip 安装时会产生版本信息
``` diff
Successfully built paddlesci
Installing collected packages: paddlesci
Attempting uninstall: paddlesci
Found existing installation: paddlesci 1.0.1.dev257+g7bf0c772.d20231205
Uninstalling paddlesci-1.0.1.dev257+g7bf0c772.d20231205:
+      Successfully uninstalled paddlesci-1.0.1.dev257+g7bf0c772.d20231205
+ Successfully installed paddlesci-1.0.1.dev257+g7bf0c772.d20231205
```
=> [Fea] Add setuptools_scm to manger version of paddlesci

docs/requirements.txt
Others 
Docs 
1. 移除`docs/requirements.txt` 中对 mkdocs 的版本限制，否则只能安装老版本的 mkdocs-material
=> [Fix] Remove restrict for version of mkdocs

docs/index.md, docs/stylesheets/extra.css, docs/zh/api/loss.md, ppsci/loss/mtl/__init__.py, ppsci/loss/mtl/relobralo.py
New features
APIs 
1. 添加多目标优化算法 ReloBRalo：https://arxiv.org/abs/2110.09813
2. 更细首页案例列表
3. 更新 css 样式，原有百分比在某些显示器上显示较窄
=> [Fea] Add ReloBRalo

docs/zh/api/experimental.md, ppsci/experimental/__init__.py, ppsci/experimental/math_module.py
New features
APIs 
1. 添加基于 [Caputo_fractional_derivative](https://en.wikipedia.org/wiki/Fractional_calculus#Caputo_fractional_derivative) 定义的一维分数阶微分功能`fractional_diff` 和对应文档
2. 移动与 `gaussian_integrate` 相关的函数至其函数内部，并加入积分上下限相反时对结果取负数的判断逻辑
=> [Fea] Add fractional diff

ppsci/geometry/mesh.py
Bug fixes 
APIs 
1. 根据 PaddlePaddle/Paddle#59518，修改 sdf 和 area 的数据类型为 paddle 默认类型，否则会触发大量的类型提升至 float64 的警告
=> [Fix] Fix float type from fp64 to fp32 for area and sdf

ppsci/data/process/transform/preprocess.py
Others 
Docs 
https://github.com/PaddlePaddle/PaddleScience/issues/686 No. 1
文档补全快速方案：
1. 安装
- pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
- pip install paddlepaddle -i https://pypi.tuna.tsinghua.edu.cn/simple
2. 找到要补全代码的文档
3. 打开文心一言：
```
请帮我补全代码注释部分。注释需要包含几个部分：
1. 说明：用于说明代码的用途
2. 参数（Args）：用于说明函数/类的参数信息
3. 返回（Returns）：用于说明该函数/类的返回值
5. 样例（Examples）：用于说明函数/类的使用方法
请补全缺失的信息，如果已有的描述不够完整，请补充的更为完整
需要补全的代码是{codes}
```
4. 根据结果微调，你可以加一些额外的要求，例如
- 当前的说明内容不完整，请补充的更多一些
- 当前的样例不够完整，请给出一个能够直接调用的样例代码
5. 验证
你可以执行并验证代码、预览文档。
=> 【PPSCI Doc No.1】ppsci.data.process.transform.CropData

examples/hpinns/functions.py, ppsci/data/dataset/array_dataset.py, ppsci/data/dataset/trphysx_dataset.py, ppsci/utils/symbolic.py
Bug fixes
Others 
1. 修复部分输入数据类型与全局默认类型不匹配，导致部分案例运行时，终端不断打印自动类型提升的问题
2. 修复 `symbolic` 模块中的两处BUG
=> [Fix] Fix weight dtype and bug in symbolic

ppsci/loss/func.py, ppsci/loss/integral.py, ppsci/loss/l1.py, ppsci/loss/l2.py, ppsci/loss/mae.py, ppsci/loss/mse.py
=> 【PPSCI Doc No.75, 77-85】

docs/zh/examples/amgnet.md, docs/zh/examples/aneurysm.md, docs/zh/examples/bracket.md, docs/zh/examples/bubble.md, docs/zh/examples/cfdgcn.md, docs/zh/examples/control_arm.md, docs/zh/examples/cylinder2d_unsteady.md, docs/zh/examples/cylinder2d_unsteady_transformer_physx.md, docs/zh/examples/deepcfd.md, docs/zh/examples/deeponet.md, docs/zh/examples/epnn.md, docs/zh/examples/hpinns.md, docs/zh/examples/labelfree_DNN_surrogate.md, docs/zh/examples/lorenz.md, docs/zh/examples/nowcastnet.md, docs/zh/examples/phylstm.md, docs/zh/examples/rossler.md, docs/zh/examples/tempoGAN.md, docs/zh/examples/topopt.md, docs/zh/install_setup.md, ppsci/experimental/math_module.py
Others 
Docs 
1. 所有文档中 `wget` 命令后面添加 `-nc` 参数，跳过已经存在的文件，防止多次执行时重复下载；`curl` 命令由于没有类似的功能因此不作改变。
2. 将 `math_module` 里 `Literal` 改为兼容 python 3.7 写法
=> [Doc] add -nc to 'wget' for skipping files already exist

ppsci/constraint/boundary_constraint.py, ppsci/constraint/initial_constraint.py, ppsci/constraint/integral_constraint.py, ppsci/constraint/interior_constraint.py, ppsci/constraint/periodic_constraint.py, ppsci/data/dataset/csv_dataset.py, ppsci/data/dataset/mat_dataset.py, ppsci/loss/integral.py, ppsci/loss/l1.py, ppsci/loss/l2.py, ppsci/loss/mae.py, ppsci/loss/mse.py
Others 
APIs 
1. 当 constraint 未指定 `weight_dict` 时，其构建出的 `dataset.__getitem__()` 返回的 weight 为空字典，而非全 1 的 ndarray，此时在 loss 计算时可跳过此类冗余的 “乘1” 计算。
=> [Enh] Avoid multiplication with weight 1 if weight is None

docs/zh/api/utils/writer.md, docs/zh/overview.md, ppsci/utils/__init__.py, ppsci/utils/writer.py, test/utils/test_symbolic.py, test/utils/test_writer.py
Others 
APIs 
1. 添加`utils.writer`模块，负责以一定格式保存数据至指定路径文件（现仅添加 csv 保存函数）
=> [Fea] Add writer module

ppsci/data/__init__.py, ppsci/solver/printer.py, ppsci/solver/solver.py, ppsci/solver/train.py, ppsci/utils/save_load.py, ppsci/visualize/plot.py, ppsci/visualize/vtu.py
Others 
Others 
1. 通过使用`global_step`代替`iter_id`，修复了`iters_per_epoch`较小的情况下，`log_freq`基本无法起到增大日志打印间隔，而实际打印过多信息导致日志文件较大、内容过多、查看不方便的问题。
2. 将日志开头的`"Epoch"`和`"Iter"`后的进度数字进行右对齐，统一数字占位长度；并删除Iter后的多余冒号`:`
3. 所有文件保存路径打印格式统一增加冒号`:`
4. 考虑到`ips:`指标后的`samples/s`单位字符串意义不大但占用较长字符位数，将其删除；在基本不影响benchmark的前提下，保留小数点后5位改为2位
5. `iters_per_epoch`较小的情况下，`latest`模型保存信息会输出多次影响日志内容，因此将其改为只在训练开始的第一个epoch输出，并给出对应提示
- 修改前
- 修改后
=> [Fix] Update for better logging information

ppsci/arch/cfdgcn.py, ppsci/arch/unetex.py, ppsci/data/dataset/airfoil_dataset.py, ppsci/data/dataset/cylinder_dataset.py
Others 
Others 
refine comments of `ppsci.data.dataset.MeshAirfoilDataset`, `ppsci.data.dataset.MeshCylinderDataset`, `ppsci.arch.UNetEx`, `ppsci.arch.CFDGCN` .
- https://github.com/PaddlePaddle/PaddleScience/issues/686
=> 【PPSCI Doc No.10、11、30】

docs/zh/api/utils/writer.md, mkdocs.yml, ppsci/utils/__init__.py, ppsci/utils/writer.py
New features
APIs 
1. 添加将数组保存至tecplot格式文件的功能
2. 统一参数`file_path`为`filename`和`alias_dict`的含义
=> [Fea] Add save_tecplot_file

docs/zh/examples/biharmonic2d.md, docs/zh/examples/bracket.md, examples/biharmonic2d/biharmonic2d.py, ppsci/autodiff/ad.py, ppsci/equation/pde/heat_exchanger.py, ppsci/equation/pde/linear_elasticity.py, ppsci/solver/solver.py, ppsci/utils/symbolic.py
Function optimization 
APIs 
1. 通过融合微分结点，一次性计算出微分分子对其它变量的所有相关微分项，代替多次微分调用，提升微分计算速度
2. 更新 线弹性方程文档 bracket 文档
3. 解决 biharmonic2d 案例读取速度过慢的问题，并更新文档
=> [Fea] Support derivative nodes fusing for any order

ppsci/autodiff/ad.py, ppsci/equation/pde/base.py, ppsci/utils/symbolic.py, test/utils/test_symbolic.py
Bug fixes
APIs 
1. 添加 fuse_derivative 单测以及修复某些corner case会导致一直在合并结点的情况
2. 优化 jacobian 对多输入变量求解判断，跳过已缓存的结果
=> [Fix] Fix fuse derivative corner case and add UT

ppsci/arch/base.py
Others
Docs
补充 ppsci.arch.Arch 中的示例代码
关联 PR https://github.com/PaddlePaddle/PaddleScience/issues/686
@HydrogenSulfate 
请评审 ～
=> 【PPSCI Doc No.12、13、14、15、16、17】ppsci.arch.Arch

docs/zh/user_guide.md, ppsci/solver/solver.py
New features
APIs 
1. 新增微调接口 `Solver.finetune(pretrained_model_path: str)`，并更新对应文档
=> [Enh] Add finetune interface

ppsci/arch/phylstm.py
Others
Docs
完善 ppsci.arch.DeepPhyLSTM 的示例 ～
由于对此模型的具体应用还不熟悉，请帮忙看看这样修改是否合适 ～
关联 PR https://github.com/PaddlePaddle/PaddleScience/issues/686
@HydrogenSulfate 请评审 ～
=> 【PPSCI Doc No.20】ppsci.arch.DeepPhyLSTM	

examples/bubble/bubble.py, ppsci/utils/expression.py
Bug fixes
APIs 
1. `visu_forward` 结尾固定清除微分缓存，否则如果expr_dict为None而微分操作注册到了model内，则可能会导致显存缓慢增大最终溢出
=> [Fix] Clear differentiation cache in visu_forward to avoid OOM problem

README.md, docs/index.md, docs/zh/install_setup.md
Others 
Docs 
1. README 安装方式更新为3种
2. 添加近期新的PR contributors，@ooooo-create, @megemini, @DUCH714, @zlynna
=> [Doc] Add more contrib and more installtion method

docs/zh/development.md, docs/zh/examples/biharmonic2d.md, docs/zh/tutorials.md, examples/biharmonic2d/biharmonic2d.py, examples/biharmonic2d/conf/biharmonic2d.yaml, examples/bubble/bubble.py, mkdocs.yml, ppsci/arch/activation.py, ppsci/arch/afno.py, ppsci/arch/base.py, ppsci/arch/embedding_koopman.py, ppsci/arch/epnn.py, ppsci/arch/gan.py, ppsci/arch/nowcastnet.py, ppsci/arch/physx_transformer.py, ppsci/data/__init__.py, ppsci/data/dataset/airfoil_dataset.py, ppsci/data/dataset/array_dataset.py, ppsci/data/dataset/csv_dataset.py, ppsci/data/dataset/cylinder_dataset.py, ppsci/data/dataset/era5_dataset.py, ppsci/data/dataset/mat_dataset.py, ppsci/data/dataset/npz_dataset.py, ppsci/data/dataset/radar_dataset.py, ppsci/data/dataset/trphysx_dataset.py, ppsci/data/dataset/vtu_dataset.py, ppsci/solver/train.py, ppsci/utils/misc.py, ppsci/utils/symbolic.py
Others 
Docs 
1. 首页添加[学习资料]章节
2. 所有`Dataset`子类添加`batch_index`标记，表示是否支持使用批下标进行索引，若支持则将`DataLoader`的`auto_collation`的默认值设置为`False`，从而通过单次批下标索引代替多次单int下标索引，减少`Dataset.__getitem__`的调用次数
3. 更正部分代码的docstring
4. `Solver.plot_loss_history`绘制时将legend图注放至到曲线图的外部右侧，避免遮挡曲线，并设置dpi提高图像分辨率
=> [Doc] Add tutorial and fix docs

ppsci/arch/nowcastnet.py, ppsci/arch/phycrnet.py, ppsci/arch/uscnn.py
Others 
Docs 
1. 更新copyright和PhyCRNet文档
=> [Fix] Update copyright and docstrings

docs/zh/examples/bubble.md, ppsci/visualize/vtu.py
Others
Docs
- No.106
- fix typo in `docs/zh/examples/bubble.md`
link #686
=> 【PPSCI Doc No.106】update doc for `ppsci.visualize.save_vtu_from_dict`

ppsci/visualize/plot.py
Others
Docs
No.108-109
link #686
=> 【PPSCI Doc No.108-109】update doc for `ppsci.visualize.save_plot_from_1d_dict` and `ppsci.visualize.save_plot_from_3d_dict`

docker/Dockerfile, docker/run.sh, docs/zh/install_setup.md
Others
Others
remove python3.7 in docker
- update python version to 3.9
- pymesh中依赖 `numpy.testing.Tester`
``` python
from numpy.testing import Tester 
```
numpy 1.25及以后废弃了 [`Tester`](https://numpy.org/doc/stable/release/1.25.0-notes.html)
=> remove python3.7 in docker

ppsci/visualize/vtu.py
=> 【PPSCI Doc No.107】update doc for `ppsci.visualize.save_vtu_to_mesh`

ppsci/data/__init__.py, ppsci/optimizer/lr_scheduler.py, ppsci/optimizer/optimizer.py, ppsci/solver/eval.py, ppsci/solver/solver.py, ppsci/utils/callbacks.py, ppsci/utils/config.py, pyproject.toml, requirements.txt, test/experimental/test_gaussian_integrate.py, test/experimental/test_trapezoid_integrate.py, test/utils/test_config.py, test/utils/test_writer.py
APIs 
内容主要来自 #737 的部分commit，完成 <https://github.com/PaddlePaddle/PaddleScience/pull/233#pullrequestreview-1358566131> 的TODO
1. 在callbacks中添加对config的检查，当检查项不符合时抛出错误并退出程序（必须手动调用sys.exit退出，因为hydra的callback机制会将抛出的错误转为warnings），并添加对应单测
2. 对部分函数和打印信息进行优化
=> [Enh] add validation for hydra config

pyproject.toml, requirements.txt
Bug fixes
Others 
specify pydantic >= 2.5.x or field_validator can not be imported from pydantic 1.x version
=> [Fix] Specify pydantic >= 2.5.x

examples/yinglong/README.md, examples/yinglong/predict_12layers.py, examples/yinglong/timefeatures.py
New features
Others
add YingLong model
TODO:
=> add YingLong model

docs/zh/examples/bubble.md, examples/bubble/bubble.py
Others
1. bubble 案例在预测前设置 `create_graph=False` 防止OOM
=> [Fix] Set create_graph=False before eval in bubble example

examples/epnn/functions.py, ppsci/data/__init__.py, ppsci/optimizer/lr_scheduler.py
Bug fixes
APIs 
1. 恢复 `SchedulerList` 的 `by_epoch` 参数
2. 修复 EPNN 案例的BUG，输入的数据类型改为 `numpy.ndarray`
=> [Fix] restore 'by_epoch' for SchedulerList and fix EPNN

README.md, docs/index.md, jointContribution/graphcast/README.md, jointContribution/graphcast/utils.py
Others 
Docs 
1. 格式化 GraphCast 的代码和文档，并更新案例链接至首页
=> [Doc] Update Graphcast to document

deploy/python_infer/base.py, examples/yinglong/README.md, examples/yinglong/conf/yinglong_12.yaml, examples/yinglong/conf/yinglong_24.yaml, examples/yinglong/predict_12layers.py, examples/yinglong/predict_24layers.py, examples/yinglong/predictor.py
Others 
APIs 
1. Yinglong 推理类代码从 `base.Predictor` 继承
2. 推理参数改为 yaml 控制
=> [Refine] Refine yinglong code

ppsci/data/dataset/vtu_dataset.py
Others 
Docs 
https://github.com/PaddlePaddle/PaddleScience/issues/686
=> 【PPSCI Doc No.9】	ppsci.data.dataset.VtuDataset

deploy/python_infer/base.py, deploy/python_infer/pinn_predictor.py, docs/zh/user_guide.md, examples/aneurysm/aneurysm.py, examples/aneurysm/conf/aneurysm.yaml, ppsci/solver/solver.py
New features
APIs 
1. 模型导出功能添加导出onnx的选项
2. pinn_predictor 支持onnx(cpu+gpu)和TensorRT推理功能
3. 使用文档添加onnx模型导出和tensorrt推理相关内容
=> [Fea] Support onnx and TensorRT inference

docs/zh/examples/topopt.md, examples/topopt/conf/topopt.yaml, examples/topopt/topopt.py, examples/topopt/topoptmodel.py
Others
Others
https://github.com/PaddlePaddle/PaddleScience/issues/788
=> 【PPSCI Export&Infer No. 29】 add export and inference

ppsci/arch/activation.py, ppsci/utils/symbolic.py
Bug fixes
Others 
1. 修复CPU运行时仍然会有1.2G GPU显存占用的问题。经排查问题出在两个部分
- `ppsci/arch/activation.py`内全局变量`act_func_dict`初始化时，包含了含参激活层`Swish`，这会触发paddle内部的初始化，导致显存占用。将`Swish`改为lazy初始化后解决。
- `ppsci/utils/symbolic.py`中的全局变量`SYMPY_TO_PADDLE`初始化时将`paddle.zeros([])`作为partial参数对`paddle.heaviside`进行了装饰，因此也会触发paddle内部的初始化，导致显存占用。将这一包装行为放至`OperatorNode.__init__`，让其变成lazy初始化后解决。
修改前（出现红框中的内容表示触发了paddle内部的初始化，显存被占用）：
修改后：
=> [Fix] Fix gpu occupying when running with cpu

docs/zh/examples/laplace2d.md, examples/laplace/conf/laplace2d.yaml, examples/laplace/laplace2d.py
Others
Others
- https://github.com/PaddlePaddle/PaddleScience/issues/788
=> 【PPSCI Export&Infer No.4】laplace2d

deploy/python_infer/base.py, docs/zh/examples/labelfree_DNN_surrogate.md, docs/zh/user_guide.md, examples/pipe/poiseuille_flow.py
Others 
Docs 
1. 在 #795 中修复了含参激活层`Swish`的参数被错误地共享的问题，本PR重新训练使用了该激活函数的pipe案例，并上传新的预训练权重`poiseuille_flow_pretrained.pdparams`
2. pipe案例绘图时，固定保留2位有效数字，并根据 https://github.com/mwaskom/seaborn/issues/3462#issuecomment-1742056756 ，建议安装>=0.13.0版本的`seaborn`
3. 重新整理使用文档中的推理相关内容
=> [Doc] Fix pipe document & refine inference guide

docs/zh/examples/lorenz.md, docs/zh/examples/rossler.md, examples/lorenz/conf/transformer.yaml, examples/lorenz/train_transformer.py, examples/rossler/train_transformer.py, ppsci/arch/physx_transformer.py
Bug fixes
Others
修复lorenz模型的导出和推理问题
TODO：
=> fix lorenz/rossler export and infer

ppsci/utils/misc.py, ppsci/utils/save_load.py, ppsci/utils/symbolic.py
Others 
Docs 
1. Refine code an docstrings and notes
=> [Doc] Refine code an docstrings

ppsci/data/__init__.py
APIs 
1. 允许dataloader_cfg内仅指定`batch_size`
=> Allow initialize dataloader without specifying 'sampler'

ppsci/data/dataset/__init__.py, ppsci/data/dataset/mrms_dataset.py
Others
APIs
1. Add dataset of loading MRMS.
=> [Add]MRMSDataset

ppsci/geometry/mesh.py
Others
Docs
任务链接：#686 No. 58-60
完善 ppsci.geometry.Mesh内from_pymesh、translate、scale函数
=> 【PPSCI Doc No.58、59、60】Mesh.from_pymesh、translate、scale

ppsci/data/dataset/radar_dataset.py
Others
Others
Specify dtype of 'vis' to avoide it be created as dtype np.float64
=> [Fix]dtype of RadarDataset's data

ppsci/equation/pde/base.py
Others
Docs
补全了以下api的参数、返回值、Examples：
ppsci.equation.PDE.parameters
ppsci.euqation.PDE.set_state_dict
ppsci.equation.PDE.state_dict
另，api描述中强调了learnable parameters
=> 【PPSCI Doc No.38-40】

ppsci/arch/mlp.py, ppsci/utils/logger.py, ppsci/utils/symbolic.py, ppsci/utils/writer.py, ppsci/visualize/plot.py, ppsci/visualize/vtu.py
Bug fixes
Others 
1. `os.path.isdir`会检查给定的文件夹路径是否真实存在，而不是字符串本身的合法性检查，故使用`len`代替
=> [Fix] Replace os.path.isdir with len

ppsci/constraint/boundary_constraint.py, ppsci/constraint/initial_constraint.py, ppsci/constraint/integral_constraint.py, ppsci/constraint/interior_constraint.py, ppsci/constraint/periodic_constraint.py, ppsci/geometry/sampler.py, ppsci/validate/geo_validator.py
Others 
APIs 
1. 添加 Halton 准随机采样方法（想比random伪随机方法，生成的点会更均匀），如下所示
``` py
import ppsci
rect = ppsci.geometry.Rectangle([-1, -1], [1, 1])
round_ = ppsci.geometry.Disk([0, 0], 1.0)
rect_halton_points = rect.sample_interior(
10000,
"Halton",
criteria=lambda x, y: (x > 0) & (y > -0.5),
)
round_halton_points = round_.sample_interior(
10000,
"Halton",
criteria=lambda x, y: (x > 0.5) & (y < 0.5),
)
ppsci.visualize.save_vtu_from_dict(
"rect_halton_points.vtu",
rect_halton_points,
("x", "y"),
("x", "y"),
)
ppsci.visualize.save_vtu_from_dict(
"round_halton_points.vtu",
round_halton_points,
("x", "y"),
("x", "y"),
)
```
=> [Enh] Add quasi-random sampling: Halton

docs/zh/api/loss/mtl.md, docs/zh/examples/viv.md, ppsci/geometry/timedomain.py, ppsci/loss/mtl/__init__.py, ppsci/loss/mtl/agda.py, ppsci/loss/mtl/base.py, ppsci/loss/mtl/relobralo.py, ppsci/loss/mtl/sum.py, ppsci/solver/solver.py, ppsci/solver/train.py, ppsci/utils/save_load.py
APIs 
1. 添加`mtl.Sum`类，并将默认总loss计算逻辑移动至该类中，简化`train.py`的代码；
2. 完善`mtl`下部分类的类型注解；
3. `Solver`添加对`LBFGS`优化器、`mtl`部分类与自动混合精度之间的兼容性检查；
4. `timedomain.py`内的`string`类型改为`str`；
5. `dist_wrapper`补充对symbolic module转换后的含参函数模型进行包装；
6. `load_pretrain`函数支持自动下载`*.pdeqn`文件，如viv案例无需再手动下载文件。
=> [Enh] Refactor sum aggregator

ppsci/geometry/geometry.py
Others
Others
对以下文档进行了补全:
ppsci.geometry.Geometry.__and__
ppsci.geometry.Geometry.__or__
ppsci.geometry.Geometry.__sub__
ppsci.geometry.Geometry.__str__
ppsci.geometry.Geometry.difference
ppsci.geometry.Geometry.intersection
ppsci.geometry.Geometry.is_inside
ppsci.geometry.Geometry.on_boundary
ppsci.geometry.Geometry.periodic_point
ppsci.geometry.Geometry.random_boundary_points
ppsci.geometry.Geometry.random_points
ppsci.geometry.Geometry.sample_boundary
ppsci.geometry.Geometry.sample_interior
ppsci.geometry.Geometry.sdf_derivatives
ppsci.geometry.Geometry.uniform_boundary_points
ppsci.geometry.Geometry.uniform_points
ppsci.geometry.Geometry.union
=> 【PPSCI Doc No.41-57】

ppsci/solver/solver.py
APIs
1. `Solver.export`函数添加`skip_prune_program`参数，避免如viv类的案例的导出报错问题。
=> [Enh] Add skip_prune_program arg for Solver.export

docs/zh/examples/viv.md, examples/fsi/conf/viv.yaml, examples/fsi/viv.py, ppsci/utils/symbolic.py
Others
Others
- [](https://github.com/PaddlePaddle/PaddleScience/issues/788#top) #788 
因为需要将equation导出  就在 ComposedNode 加入了paddle.nn.LayerList，不然导出找不到里面的参数
equation导出时，模型裁剪也会出问题，我就先跳过了
=> 【PPSCI Export&Infer No.23】viv

docs/index.md, docs/javascripts/contributors.js, mkdocs.yml, ppsci/equation/pde/base.py, ppsci/geometry/geometry.py, ppsci/geometry/timedomain.py
Others 
Docs 
1. 首页贡献者使用js代码自动生成，代替手动添加；
2. 修复部分docstring和typehint的问题。
=> [Doc] Add more contributors and refine several docstrings

ppsci/geometry/pointcloud.py
Others
Others
对以下文档进行了补全:
ppsci.geometry.PointCloud.translate
ppsci.geometry.PointCloud.scale
ppsci.geometry.PointCloud.random_boundary_points
ppsci.geometry.PointCloud.random_points
ppsci.geometry.PointCloud.uniform_points
=> 【PPSCI Doc No.61-65】

docs/zh/examples/euler_beam.md, docs/zh/user_guide.md, examples/euler_beam/conf/euler_beam.yaml, examples/euler_beam/euler_beam.py, ppsci/equation/pde/base.py, ppsci/loss/mtl/sum.py
Others 
Docs 
1. 修复使用文档中 MKLDNN 的拼写错误；
2. 合并tensorboard、visualdl、wandb使用教程为一个章节；
3. 将`Sum`的求和行为进行微调，并更改euler_beam的随机种子为42，使得收敛精度不低于原本的精度(8e-4-->0.00058)；
4. 由于现有paddle已支持eulerbeam在非组合模式下运行，因此删除euler_beam的组合开关。
=> [Doc] Fix description for mkldnn

ppsci/utils/callbacks.py, ppsci/utils/config.py
New features
Others 
1. 支持以命令行的方式开启组合算子模式：`python xxx.py +prim=True`
=> [Enh] Support enabling prim via CLI

ppsci/arch/afno.py, ppsci/arch/physx_transformer.py, ppsci/autodiff/ad.py, ppsci/equation/pde/base.py, ppsci/geometry/mesh.py, ppsci/geometry/timedomain.py, ppsci/utils/misc.py
Others
Docs
补全 https://github.com/PaddlePaddle/PaddleScience/issues/686 中的23、25-29、31-34、97 api的文档
其中，第32 ppsci.autodiff.Jacobians.__call__ 没看出来有问题。
97 代码示例单独测试没问题 doctest有问题
=> 【PPSCI Doc No.23、25-29、31-34、97】

ppsci/utils/config.py
Others 
Others 
1. pydantic 2.4 已不推荐使用`FieldValidationInfo`，因此根据官网要求，改为`ValidationInfo`。
=> [Fix] Replace deprecated 'FieldValidationInfo' with 'ValidationInfo'

ppsci/loss/func.py, test/loss/func.py
APIs 
1. 对`FunctionalLoss`所包装的函数的返回值进行检查，确保其类型为张量。
=> [Fix] Check return type of FunctionalLoss

docs/zh/examples/biharmonic2d.md, examples/biharmonic2d/biharmonic2d.py, examples/biharmonic2d/conf/biharmonic2d.yaml
Others
Others
- [](https://github.com/PaddlePaddle/PaddleScience/issues/788#top) #788
=> 【PPSCI Export&Infer No.24】 biharmonic2d

README.md, docs/index.md, ppsci/solver/eval.py
Others
Docs
1. 添加光孤子和光纤怪波案例到首页文档
2. eval函数添加必要的注释
=> [Doc] Add anno for eval

docs/zh/install_setup.md
Others 
Docs 
1. 考虑到PyMesh包及其submodule较大，全部clone较为费时，因此提供压缩包下载的方式
=> [Doc] Update pymesh install package

examples/NLS-MB/NLS-MB_optical_rogue_wave.py, examples/NLS-MB/NLS-MB_optical_soliton.py, ppsci/__init__.py
New features
Others 
1. 支持解析yaml配置中的numpy下的属性，如在numpy中填写`np.pi`并在程序运行时被解析成`np.pi`浮点常量。
2. 基于推理模型导出顺序的修复PR<https://github.com/PaddlePaddle/Paddle/pull/63791>删除手动排序的代码。
=> [Enh] Add numpy solver in config solvers

docs/index.md, ppsci/arch/cuboid_transformer.py
Others 
Docs 
1. 添加 IJCAI 2024 比赛链接到首页；
2. 修复部分docstring格式。
=> [Doc] Add IJCAI 2024 CAR competition to inedx.md and fix docstrings

deploy/python_infer/__init__.py, docs/zh/api/depoly/python_infer.md, mkdocs.yml, ppsci/arch/cuboid_transformer.py
Others 
Docs 
1. 添加deploy模块文档
2. 修复ppsci/arch/cuboid_transformer.py docstring问题
=> [Doc] Add inference document

docs/zh/examples/tempoGAN.md, examples/tempoGAN/conf/tempogan.yaml, examples/tempoGAN/tempoGAN.py
Others
Others
- [](https://github.com/PaddlePaddle/PaddleScience/issues/788)#788
- 不知道为什么剪枝后 会找不到executor里的 变量名，就先跳过了
=> 【PPSCI Export&Infer No.21】tempoGAN

docs/zh/examples/shock_wave.md, examples/shock_wave/conf/shock_wave_Ma0.728.yaml, examples/shock_wave/conf/shock_wave_Ma2.0.yaml, examples/shock_wave/shock_wave.py
Others
Others
- [](https://github.com/PaddlePaddle/PaddleScience/issues/788)#788
=> 【PPSCI Export&Infer No.20】shock_wave

ppsci/equation/pde/base.py, ppsci/equation/pde/biharmonic.py, ppsci/equation/pde/heat_exchanger.py, ppsci/equation/pde/laplace.py, ppsci/equation/pde/linear_elasticity.py, ppsci/equation/pde/navier_stokes.py, ppsci/equation/pde/nls_m_b.py, ppsci/equation/pde/normal_dot_vec.py, ppsci/equation/pde/poisson.py, ppsci/equation/pde/viv.py, ppsci/utils/symbolic.py, test/equation/test_detach.py, test/equation/test_pde_base.py, test/utils/test_symbolic.py
Others 
APIs 
1. 支持方程初始化时指定`detach_keys`，使得梯度不会通过这些key对应的变量反向传播，并添加对应单测。
```mermaid
graph TD;
x & y-->u & v;
x & u-->u__x;
y & v-->v__y;
u__x & u --> o1;
v__y & v --> o2;
o1 & o2 --> z;
```
当`detach_keys`为`("u", "v__y")`时，计算关系会变为下图（新增两条detach路径）。
```mermaid
graph TD;
x & y-->u & v;
x & u-->u__x;
y & v-->v__y;
u --> |detach| u_detach([u_detach]);
u__x & u_detach --> o1;
v__y --> |detach| v__y_detach([v__y_detach]);
v__y_detach & v --> o2;
o1 & o2 --> z;
```
=> [Fea] Support detach_keys argument for all PDE

docs/zh/examples/darcy2d.md, examples/darcy/conf/darcy2d.yaml, examples/darcy/darcy2d.py
Others
Others
#788 
推理时有警告W0515 17:37:30.157079 45856 gpu_cpu_map_matmul_to_mul_pass.cc:425] matmul op not support broadcast, please check inputs'shape.
但不影响输出结果
=> 【PPSCI Export&Infer No.13】 darcy2d

docs/zh/examples/hpinns.md, examples/hpinns/conf/hpinns.yaml, examples/hpinns/holography.py
=> Add export & inference for hPINNs

docs/zh/examples/deeponet.md, examples/operator_learning/conf/deeponet.yaml, examples/operator_learning/deeponet.py, ppsci/geometry/geometry.py
Others
APIs 
1. 为DeepONet添加导出和推理代码
2. 完善geometry.py的docstring
=> 【PPSCI Export&Infer No.2】Add export & inference for DeepONet

docs/zh/examples/hpinns.md, examples/hpinns/holography.py, examples/hpinns/plotting.py
Others
Others
1. update plotting of hpinn's inference
=> [Upadte]update plotting of hpinn's inference

examples/fpde/conf/fractional_poisson_2d.yaml, examples/fpde/fractional_poisson_2d.py, ppsci/geometry/geometry.py
Others 
APIs 
1. 将 fractional poisson 2d 案例迁移至 hydra 配置下，并简化相关代码。
=> [Fix] Fix fractional poisson 2d

docs/zh/development.md, docs/zh/examples/viv.md, docs/zh/user_guide.md, examples/fsi/conf/viv.yaml, examples/fsi/viv.py, ppsci/arch/cuboid_transformer.py, ppsci/experimental/math_module.py, ppsci/solver/solver.py, ppsci/utils/save_load.py
Bug fixes, Others 
Docs, APIs 
1. 更新 viv 案例代码，并添加基于 viv 的 optuna 自动超参搜索使用教程。
2. 修复几处文档和 API 错误。
=> [Doc&Fix] Update config doc and correct API

docs/zh/examples/earthformer.md, docs/zh/examples/nowcastnet.md, examples/nowcastnet/conf/nowcastnet.yaml, examples/nowcastnet/nowcastnet.py, ppsci/arch/nowcastnet.py
Others 
Others 
- [](https://github.com/PaddlePaddle/PaddleScience/issues/788#top) #788
=> 【PPSCI Export&Infer No.35】nowcastnet

docs/zh/api/arch.md, docs/zh/examples/allen_cahn.md, examples/allen_cahn/allen_cahn_causal.py, examples/allen_cahn/allen_cahn_default.py, examples/allen_cahn/allen_cahn_piranet.py, examples/allen_cahn/allen_cahn_piratenet.py, examples/allen_cahn/conf/allen_cahn_piranet.yaml, examples/allen_cahn/conf/allen_cahn_piratenet.yaml, mkdocs.yml, ppsci/arch/__init__.py, ppsci/arch/mlp.py
New features
APIs 
1. 添加基于 PiraNet 模型的 allen_cahn 案例，并更新案例文档
2. 更新几处样例代码
=> [Fea] Add PirateNet and update allen_cahn document

examples/allen_cahn/allen_cahn_defalut_ntk.py, examples/allen_cahn/allen_cahn_sota.py, examples/allen_cahn/conf/allen_cahn_defalut_ntk.yaml, examples/allen_cahn/conf/allen_cahn_sota.yaml, ppsci/arch/mlp.py, ppsci/loss/mse.py, ppsci/loss/mtl/__init__.py, ppsci/loss/mtl/ntk.py
=> Add allen cahn sota

README.md, docs/index.md, docs/zh/examples/xpinns.md, examples/xpinn/conf/xpinn.yaml, examples/xpinn/plotting.py, examples/xpinn/xpinn.py, mkdocs.yml, ppsci/arch/sfnonet.py, ppsci/arch/tfnonet.py, ppsci/equation/pde/allen_cahn.py
Others 
Docs 
1. 完善XPINN文档和代码，并添加至首页案例列表
=> [Doc] Add evaluation for xpinn and add to homepage

deploy/python_infer/__init__.py, deploy/python_infer/pinn_predictor.py, ppsci/geometry/mesh.py
Others 
Docs 
1. 添加 PINNPredictor 的案例代码
2. 完善 Mesh 方法的typing
=> [Doc] Update example code for PINNPredictor

README.md, docs/index.md, docs/zh/examples/extformer_moe.md, examples/extformer_moe/extformer_moe_enso_train.py, examples/extformer_moe/requirements.txt, mkdocs.yml, ppsci/arch/activation.py, ppsci/arch/amgnet.py, ppsci/arch/cuboid_transformer.py, ppsci/arch/cuboid_transformer_decoder.py, ppsci/arch/cuboid_transformer_encoder.py, ppsci/arch/cuboid_transformer_utils.py, ppsci/arch/extformer_moe_cuboid.py, ppsci/arch/extformer_moe_cuboid_decoder.py, ppsci/arch/extformer_moe_cuboid_encoder.py, ppsci/arch/extformer_moe_cuboid_utils.py, ppsci/arch/extformer_moe_utils.py, ppsci/arch/mlp.py, ppsci/arch/nowcastnet.py, ppsci/arch/phycrnet.py
Bug fixes
Others
1. 修复paddle类型提升机制变动导致float与bool之间无法直接运算，需手动将bool转为float
2. 将所有的`paddle.nn.xxx`替换为`nn.xxx`
3. 添加 extformer-moe 文档至首页目录，并添加requirements.txt
=> [Fix] Fix extformer-moe

docs/zh/examples/amgnet.md, docs/zh/examples/phylstm.md, examples/deepcfd/deepcfd.py, examples/phylstm/conf/phylstm2.yaml, examples/phylstm/conf/phylstm3.yaml, ppsci/solver/solver.py
Bug fixes
Others 
1. 修复 phylstm2/3.py 配置文件缺少默认配置导致运行报错的问题，以及更新文档代码块位置
2. 修复 deepcfd 运行报错问题
3. 完善Solver内对paddle版本的警告
=> [Fix] Fix phylstm

README.md, deploy/python_infer/pinn_predictor.py, docs/zh/api/data/process/batch_transform.md, docs/zh/development.md, docs/zh/examples/adv_cvit.md, docs/zh/examples/ns_cvit.md, ppsci/solver/solver.py, ppsci/utils/config.py
Others 
Docs 
1. 修复Cvit文档相关的链接和公式问题
=> [Doc] Fix document and formulations for cvit

deploy/python_infer/base.py, ppsci/solver/solver.py, ppsci/utils/misc.py
New features
Others 
1. 基于 <https://github.com/PaddlePaddle/Paddle/pull/65813>， 支持PIR模式下的模型导出和python推理
=> [PIR] Support pir export and infer

deploy/python_infer/base.py, ppsci/solver/solver.py, ppsci/utils/callbacks.py
Bug fixes
APIs 
1. 修复`solver.predict`当batchsize为None时，未将输入转换为Tensor的BUG
2. 在运行案例前的callback中进行设备设置
=> [Fix] Fix solver.predict and device setting

README.md, docs/index.md, docs/zh/api/arch.md, docs/zh/api/utils/misc.md, docs/zh/development.md, docs/zh/examples/aneurysm.md, docs/zh/examples/bracket.md, docs/zh/examples/control_arm.md, docs/zh/reproduction.md, docs/zh/user_guide.md, examples/xpinn/plotting.py, ppsci/loss/__init__.py
Others 
Docs 
1. 更新文档域名
2. 更新开发指南
3. 更新 XPINN 字体设置
4. 添加 SPINN 到文档中
=> [Doc] Update guidance of development

ppsci/visualize/vtu.py
Bug fixes
APIs 
vtu保存文件命名添加前导0，避免paraview打开时顺序错乱
=> [Fix] Add leading zero to filename when saving vtu file

ppsci/arch/cvit.py, ppsci/solver/solver.py
Bug fixes
Others 
1. 删除导出模型时多余的参数：ignore_module
2. 将cvit_ns的assert移动到in_dynamic_mode下
=> [Fix] Remove redundant ignore_module in to_static and fix cvit_ns export
